### YamlMime:TSTypeAlias
name: ConfigurationStoresListNextResponse
uid: '@azure/arm-appconfiguration.ConfigurationStoresListNextResponse|latest-stable'
package: '@azure/arm-appconfiguration|latest-stable'
summary: Contains response data for the listNext operation.
fullName: ConfigurationStoresListNextResponse
remarks: ''
isPreview: false
isDeprecated: false
syntax: >-
  type ConfigurationStoresListNextResponse = ConfigurationStoreListResult & {
  _response: Object }
