### YamlMime:TSTypeAlias
name: KeyValuesGetResponse
uid: '@azure/arm-appconfiguration.KeyValuesGetResponse|latest-stable'
package: '@azure/arm-appconfiguration|latest-stable'
summary: Contains response data for the get operation.
fullName: KeyValuesGetResponse
remarks: ''
isPreview: false
isDeprecated: false
syntax: 'type KeyValuesGetResponse = KeyValue & { _response: Object }'
