### YamlMime:TSType
name: TrainingPollOperationState
uid: '@azure/ai-form-recognizer.TrainingPollOperationState|preview'
package: '@azure/ai-form-recognizer|preview'
summary: The state of a model creation operation.
fullName: TrainingPollOperationState
remarks: ''
isPreview: false
isDeprecated: false
type: interface
properties:
  - name: createdOn
    uid: '@azure/ai-form-recognizer.TrainingPollOperationState.createdOn|preview'
    package: '@azure/ai-form-recognizer|preview'
    summary: The Date and Time that the operation was created.
    fullName: createdOn
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'createdOn: Date'
      return:
        type: Date
        description: ''
  - name: error
    uid: '@azure/ai-form-recognizer.TrainingPollOperationState.error|preview'
    package: '@azure/ai-form-recognizer|preview'
    summary: Will exist if the operation encountered any error.
    fullName: error
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'error?: Error'
      return:
        type: Error
        description: ''
  - name: isCancelled
    uid: '@azure/ai-form-recognizer.TrainingPollOperationState.isCancelled|preview'
    package: '@azure/ai-form-recognizer|preview'
    summary: True if the operation has been cancelled.
    fullName: isCancelled
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'isCancelled?: boolean'
      return:
        type: boolean
        description: ''
  - name: isCompleted
    uid: '@azure/ai-form-recognizer.TrainingPollOperationState.isCompleted|preview'
    package: '@azure/ai-form-recognizer|preview'
    summary: True if the operation has been completed.
    fullName: isCompleted
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'isCompleted?: boolean'
      return:
        type: boolean
        description: ''
  - name: isStarted
    uid: '@azure/ai-form-recognizer.TrainingPollOperationState.isStarted|preview'
    package: '@azure/ai-form-recognizer|preview'
    summary: True if the operation has started.
    fullName: isStarted
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'isStarted?: boolean'
      return:
        type: boolean
        description: ''
  - name: lastUpdatedOn
    uid: '@azure/ai-form-recognizer.TrainingPollOperationState.lastUpdatedOn|preview'
    package: '@azure/ai-form-recognizer|preview'
    summary: The date & time that the operation state was last modified.
    fullName: lastUpdatedOn
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'lastUpdatedOn: Date'
      return:
        type: Date
        description: ''
  - name: operationId
    uid: '@azure/ai-form-recognizer.TrainingPollOperationState.operationId|preview'
    package: '@azure/ai-form-recognizer|preview'
    summary: The unique ID of this operation.
    fullName: operationId
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'operationId: string'
      return:
        type: string
        description: ''
  - name: percentCompleted
    uid: >-
      @azure/ai-form-recognizer.TrainingPollOperationState.percentCompleted|preview
    package: '@azure/ai-form-recognizer|preview'
    summary: A number between 0 and 100 representing the progress of the operation.
    fullName: percentCompleted
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'percentCompleted: number'
      return:
        type: number
        description: ''
  - name: result
    uid: '@azure/ai-form-recognizer.TrainingPollOperationState.result|preview'
    package: '@azure/ai-form-recognizer|preview'
    summary: Will exist if the operation concluded in a result of an expected type.
    fullName: result
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'result?: ModelInfo'
      return:
        type: <xref uid="@azure/ai-form-recognizer.ModelInfo" />
        description: ''
  - name: status
    uid: '@azure/ai-form-recognizer.TrainingPollOperationState.status|preview'
    package: '@azure/ai-form-recognizer|preview'
    summary: |
      The status of the operation. One of:
      - "notStarted"
      - "running"
      - "succeeded"
      - "failed"
      - "canceled"
    fullName: status
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'status: OperationStatus'
      return:
        type: <xref uid="@azure/ai-form-recognizer.OperationStatus" />
        description: ''
extends: PollOperationState&lt;<xref uid="@azure/ai-form-recognizer.ModelInfo" />&gt;
