name: ClusterQuotaConfigurationProperties
uid: '@azure/arm-eventhub.ClusterQuotaConfigurationProperties|preview'
package: '@azure/arm-eventhub|preview'
summary: Contains all settings for the cluster.
fullName: ClusterQuotaConfigurationProperties
remarks: ''
isPreview: false
isDeprecated: false
type: interface
properties:
  - name: settings
    uid: '@azure/arm-eventhub.ClusterQuotaConfigurationProperties.settings|preview'
    package: '@azure/arm-eventhub|preview'
    summary: >-
      All possible Cluster settings - a collection of key/value paired settings
      which apply to quotas and configurations imposed on the cluster.
    fullName: settings
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'settings?: undefined | [key: string]: string'
      return:
        type: 'undefined | [key: string]: string'
        description: ''
