### YamlMime:TSTypeAlias
name: ConfigurationPatchResponse
uid: '@azure/arm-eventhub.ConfigurationPatchResponse|preview'
package: '@azure/arm-eventhub|preview'
summary: Contains response data for the patch operation.
fullName: ConfigurationPatchResponse
remarks: ''
isPreview: false
isDeprecated: false
syntax: type ConfigurationPatchResponse = ClusterQuotaConfigurationProperties
