name: DisasterRecoveryConfigsGetAuthorizationRuleResponse
uid: >-
  @azure/arm-eventhub.DisasterRecoveryConfigsGetAuthorizationRuleResponse|preview
package: '@azure/arm-eventhub|preview'
summary: Contains response data for the getAuthorizationRule operation.
fullName: DisasterRecoveryConfigsGetAuthorizationRuleResponse
remarks: ''
isPreview: false
isDeprecated: false
syntax: type DisasterRecoveryConfigsGetAuthorizationRuleResponse = AuthorizationRule
