name: DisasterRecoveryConfigsListAuthorizationRulesResponse
uid: >-
  @azure/arm-eventhub.DisasterRecoveryConfigsListAuthorizationRulesResponse|preview
package: '@azure/arm-eventhub|preview'
summary: Contains response data for the listAuthorizationRules operation.
fullName: DisasterRecoveryConfigsListAuthorizationRulesResponse
remarks: ''
isPreview: false
isDeprecated: false
syntax: >-
  type DisasterRecoveryConfigsListAuthorizationRulesResponse =
  AuthorizationRuleListResult
