name: DisasterRecoveryConfigsListAuthorizationRulesNextResponse
uid: >-
  @azure/arm-eventhub.DisasterRecoveryConfigsListAuthorizationRulesNextResponse|preview
package: '@azure/arm-eventhub|preview'
summary: Contains response data for the listAuthorizationRulesNext operation.
fullName: DisasterRecoveryConfigsListAuthorizationRulesNextResponse
remarks: ''
isPreview: false
isDeprecated: false
syntax: >-
  type DisasterRecoveryConfigsListAuthorizationRulesNextResponse =
  AuthorizationRuleListResult
