### YamlMime:TSType
name: ConnectionConfigOptions
uid: '@azure/core-amqp.ConnectionConfigOptions|preview'
package: '@azure/core-amqp|preview'
summary: Describes the options that can be provided while creating a connection config.
fullName: ConnectionConfigOptions
remarks: ''
isPreview: false
isDeprecated: false
type: interface
properties:
  - name: isEntityPathRequired
    uid: '@azure/core-amqp.ConnectionConfigOptions.isEntityPathRequired|preview'
    package: '@azure/core-amqp|preview'
    summary: >-
      {boolean} [isEntityPathRequired] Indicates whether the entity path is
      required in the

      connection config.
    fullName: isEntityPathRequired
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'isEntityPathRequired?: boolean'
      return:
        type: boolean
        description: ''
