### YamlMime:TSType
name: FileQueryParquetConfiguration
uid: '@azure/storage-file-datalake.FileQueryParquetConfiguration|latest-stable'
package: '@azure/storage-file-datalake|latest-stable'
summary: Options to query file with Parquet format.
fullName: FileQueryParquetConfiguration
remarks: ''
isPreview: false
isDeprecated: false
type: interface
properties:
  - name: kind
    uid: >-
      @azure/storage-file-datalake.FileQueryParquetConfiguration.kind|latest-stable
    package: '@azure/storage-file-datalake|latest-stable'
    summary: Kind.
    fullName: kind
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'kind: "parquet"'
      return:
        type: '"parquet"'
        description: ''
