### YamlMime:TSType
name: BlobQueryArrowConfiguration
uid: '@azure/storage-blob.BlobQueryArrowConfiguration|latest-stable'
package: '@azure/storage-blob|latest-stable'
summary: >-
  Options to query blob with Apache Arrow format. Only valid for
  <xref:@azure/storage-blob.BlockBlobQueryOptions.outputTextConfiguration>.
fullName: BlobQueryArrowConfiguration
remarks: ''
isPreview: false
isDeprecated: false
type: interface
properties:
  - name: kind
    uid: '@azure/storage-blob.BlobQueryArrowConfiguration.kind|latest-stable'
    package: '@azure/storage-blob|latest-stable'
    summary: Kind.
    fullName: kind
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'kind: "arrow"'
      return:
        type: '"arrow"'
        description: ''
  - name: schema
    uid: '@azure/storage-blob.BlobQueryArrowConfiguration.schema|latest-stable'
    package: '@azure/storage-blob|latest-stable'
    summary: >-
      List of <xref:@azure/storage-blob.BlobQueryArrowField> describing the
      schema of the data.
    fullName: schema
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'schema: BlobQueryArrowField[]'
      return:
        type: <xref uid="@azure/storage-blob.BlobQueryArrowField|latest-stable" />[]
        description: ''
