name: BlobQueryParquetConfiguration
uid: '@azure/storage-blob.BlobQueryParquetConfiguration|latest-stable'
package: '@azure/storage-blob|latest-stable'
summary: >-
  Options to query blob with Parquet format. Only valid for
  <xref:@azure/storage-blob.BlockBlobQueryOptions.inputTextConfiguration>.
fullName: BlobQueryParquetConfiguration
remarks: ''
isPreview: false
isDeprecated: false
type: interface
properties:
  - name: kind
    uid: '@azure/storage-blob.BlobQueryParquetConfiguration.kind|latest-stable'
    package: '@azure/storage-blob|latest-stable'
    summary: Kind.
    fullName: kind
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'kind: "parquet"'
      return:
        type: '"parquet"'
        description: ''
