name: Pipeline
uid: '@azure/storage-blob.Pipeline|latest-stable'
package: '@azure/storage-blob|latest-stable'
summary: >
  A Pipeline class containing HTTP request policies.

  You can create a default Pipeline by calling
  <xref:@azure/storage-blob.newPipeline>.

  Or you can create a Pipeline with your own policies by the constructor of
  Pipeline.

  Refer to <xref:@azure/storage-blob.newPipeline> and provided policies before
  implementing your

  customized Pipeline.
fullName: Pipeline
remarks: ''
isPreview: false
isDeprecated: false
type: class
constructors:
  - name: Pipeline(RequestPolicyFactory[], PipelineOptions)
    uid: '@azure/storage-blob.Pipeline.constructor|latest-stable'
    package: '@azure/storage-blob|latest-stable'
    summary: >-
      Creates an instance of Pipeline. Customize HTTPClient by implementing
      IHttpClient interface.
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: >-
        new Pipeline(factories: RequestPolicyFactory[], options?:
        PipelineOptions)
      parameters:
        - id: factories
          type: RequestPolicyFactory[]
          description: '-'
        - id: options
          type: <xref uid="@azure/storage-blob.PipelineOptions" />
          description: |
            -
properties:
  - name: factories
    uid: '@azure/storage-blob.Pipeline.factories|latest-stable'
    package: '@azure/storage-blob|latest-stable'
    summary: A list of chained request policy factories.
    fullName: factories
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'factories: RequestPolicyFactory[]'
      return:
        type: RequestPolicyFactory[]
        description: ''
  - name: options
    uid: '@azure/storage-blob.Pipeline.options|latest-stable'
    package: '@azure/storage-blob|latest-stable'
    summary: Configures pipeline logger and HTTP client.
    fullName: options
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'options: PipelineOptions'
      return:
        type: <xref uid="@azure/storage-blob.PipelineOptions" />
        description: ''
methods:
  - name: toServiceClientOptions()
    uid: '@azure/storage-blob.Pipeline.toServiceClientOptions|latest-stable'
    package: '@azure/storage-blob|latest-stable'
    summary: >-
      Transfer Pipeline object to ServiceClientOptions object which is required
      by

      ServiceClient constructor.
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: function toServiceClientOptions()
      return:
        type: ServiceClientOptions
        description: The ServiceClientOptions object from this Pipeline.
