### YamlMime:TSType
name: Configuration
uid: '@azure/arm-eventhub.Configuration|latest-stable'
package: '@azure/arm-eventhub|latest-stable'
summary: Class representing a Configuration.
fullName: Configuration
remarks: ''
isPreview: false
isDeprecated: false
type: class
constructors:
  - name: Configuration(EventHubManagementClientContext)
    uid: '@azure/arm-eventhub.Configuration.constructor|latest-stable'
    package: '@azure/arm-eventhub|latest-stable'
    summary: Create a Configuration.
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'new Configuration(client: EventHubManagementClientContext)'
      parameters:
        - id: client
          type: >-
            <xref
            uid="@azure/arm-eventhub.EventHubManagementClientContext|latest-stable"
            />
          description: |
            Reference to the service client.
methods:
  - name: get(string, string, msRest.RequestOptionsBase)
    uid: '@azure/arm-eventhub.Configuration.get|latest-stable'
    package: '@azure/arm-eventhub|latest-stable'
    summary: >-
      Get all Event Hubs Cluster settings - a collection of key/value pairs
      which represent the quotas

      and settings imposed on the cluster.
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: >-
        function get(resourceGroupName: string, clusterName: string, options?:
        msRest.RequestOptionsBase)
      parameters:
        - id: resourceGroupName
          type: string
          description: Name of the resource group within the azure subscription.
        - id: clusterName
          type: string
          description: The name of the Event Hubs Cluster.
        - id: options
          type: <xref uid="msRest.RequestOptionsBase|latest-stable" />
          description: ''
      return:
        type: >-
          Promise&lt;<xref uid="Models.ConfigurationGetResponse|latest-stable"
          />&gt;
        description: Promise<Models.ConfigurationGetResponse>
  - name: >-
      get(string, string, RequestOptionsBase,
      ServiceCallback<ClusterQuotaConfigurationProperties>)
    uid: '@azure/arm-eventhub.Configuration.get_2|latest-stable'
    package: '@azure/arm-eventhub|latest-stable'
    summary: ''
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: >-
        function get(resourceGroupName: string, clusterName: string, options:
        RequestOptionsBase, callback:
        ServiceCallback<ClusterQuotaConfigurationProperties>)
      parameters:
        - id: resourceGroupName
          type: string
          description: Name of the resource group within the azure subscription.
        - id: clusterName
          type: string
          description: The name of the Event Hubs Cluster.
        - id: options
          type: RequestOptionsBase
          description: The optional parameters
        - id: callback
          type: >-
            ServiceCallback&lt;<xref
            uid="@azure/arm-eventhub.ClusterQuotaConfigurationProperties|latest-stable"
            />&gt;
          description: |
            The callback
  - name: get(string, string, ServiceCallback<ClusterQuotaConfigurationProperties>)
    uid: '@azure/arm-eventhub.Configuration.get_1|latest-stable'
    package: '@azure/arm-eventhub|latest-stable'
    summary: ''
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: >-
        function get(resourceGroupName: string, clusterName: string, callback:
        ServiceCallback<ClusterQuotaConfigurationProperties>)
      parameters:
        - id: resourceGroupName
          type: string
          description: Name of the resource group within the azure subscription.
        - id: clusterName
          type: string
          description: The name of the Event Hubs Cluster.
        - id: callback
          type: >-
            ServiceCallback&lt;<xref
            uid="@azure/arm-eventhub.ClusterQuotaConfigurationProperties|latest-stable"
            />&gt;
          description: |
            The callback
  - name: >-
      patch(string, string, ClusterQuotaConfigurationProperties,
      msRest.RequestOptionsBase)
    uid: '@azure/arm-eventhub.Configuration.patch|latest-stable'
    package: '@azure/arm-eventhub|latest-stable'
    summary: >-
      Replace all specified Event Hubs Cluster settings with those contained in
      the request body.

      Leaves the settings not specified in the request body unmodified.
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: >-
        function patch(resourceGroupName: string, clusterName: string,
        parameters: ClusterQuotaConfigurationProperties, options?:
        msRest.RequestOptionsBase)
      parameters:
        - id: resourceGroupName
          type: string
          description: Name of the resource group within the azure subscription.
        - id: clusterName
          type: string
          description: The name of the Event Hubs Cluster.
        - id: parameters
          type: >-
            <xref
            uid="@azure/arm-eventhub.ClusterQuotaConfigurationProperties|latest-stable"
            />
          description: Parameters for creating an Event Hubs Cluster resource.
        - id: options
          type: <xref uid="msRest.RequestOptionsBase|latest-stable" />
          description: ''
      return:
        type: >-
          Promise&lt;<xref uid="Models.ConfigurationPatchResponse|latest-stable"
          />&gt;
        description: Promise<Models.ConfigurationPatchResponse>
  - name: >-
      patch(string, string, ClusterQuotaConfigurationProperties,
      RequestOptionsBase, ServiceCallback<ClusterQuotaConfigurationProperties>)
    uid: '@azure/arm-eventhub.Configuration.patch_2|latest-stable'
    package: '@azure/arm-eventhub|latest-stable'
    summary: ''
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: >-
        function patch(resourceGroupName: string, clusterName: string,
        parameters: ClusterQuotaConfigurationProperties, options:
        RequestOptionsBase, callback:
        ServiceCallback<ClusterQuotaConfigurationProperties>)
      parameters:
        - id: resourceGroupName
          type: string
          description: Name of the resource group within the azure subscription.
        - id: clusterName
          type: string
          description: The name of the Event Hubs Cluster.
        - id: parameters
          type: >-
            <xref
            uid="@azure/arm-eventhub.ClusterQuotaConfigurationProperties|latest-stable"
            />
          description: Parameters for creating an Event Hubs Cluster resource.
        - id: options
          type: RequestOptionsBase
          description: The optional parameters
        - id: callback
          type: >-
            ServiceCallback&lt;<xref
            uid="@azure/arm-eventhub.ClusterQuotaConfigurationProperties|latest-stable"
            />&gt;
          description: |
            The callback
  - name: >-
      patch(string, string, ClusterQuotaConfigurationProperties,
      ServiceCallback<ClusterQuotaConfigurationProperties>)
    uid: '@azure/arm-eventhub.Configuration.patch_1|latest-stable'
    package: '@azure/arm-eventhub|latest-stable'
    summary: ''
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: >-
        function patch(resourceGroupName: string, clusterName: string,
        parameters: ClusterQuotaConfigurationProperties, callback:
        ServiceCallback<ClusterQuotaConfigurationProperties>)
      parameters:
        - id: resourceGroupName
          type: string
          description: Name of the resource group within the azure subscription.
        - id: clusterName
          type: string
          description: The name of the Event Hubs Cluster.
        - id: parameters
          type: >-
            <xref
            uid="@azure/arm-eventhub.ClusterQuotaConfigurationProperties|latest-stable"
            />
          description: Parameters for creating an Event Hubs Cluster resource.
        - id: callback
          type: >-
            ServiceCallback&lt;<xref
            uid="@azure/arm-eventhub.ClusterQuotaConfigurationProperties|latest-stable"
            />&gt;
          description: |
            The callback
