name: DisasterRecoveryConfigsGetAuthorizationRuleResponse
uid: >-
  @azure/arm-eventhub.DisasterRecoveryConfigsGetAuthorizationRuleResponse|latest-stable
package: '@azure/arm-eventhub|latest-stable'
summary: Contains response data for the getAuthorizationRule operation.
fullName: DisasterRecoveryConfigsGetAuthorizationRuleResponse
remarks: ''
isPreview: false
isDeprecated: false
syntax: >-
  type DisasterRecoveryConfigsGetAuthorizationRuleResponse = AuthorizationRule &
  { _response: Object }
