name: DisasterRecoveryConfigsGetResponse
uid: '@azure/arm-eventhub.DisasterRecoveryConfigsGetResponse|latest-stable'
package: '@azure/arm-eventhub|latest-stable'
summary: Contains response data for the get operation.
fullName: DisasterRecoveryConfigsGetResponse
remarks: ''
isPreview: false
isDeprecated: false
syntax: >-
  type DisasterRecoveryConfigsGetResponse = ArmDisasterRecovery & { _response:
  Object }
