### YamlMime:TSTypeAlias
name: DisasterRecoveryConfigsListNextResponse
uid: '@azure/arm-eventhub.DisasterRecoveryConfigsListNextResponse|latest-stable'
package: '@azure/arm-eventhub|latest-stable'
summary: Contains response data for the listNext operation.
fullName: DisasterRecoveryConfigsListNextResponse
remarks: ''
isPreview: false
isDeprecated: false
syntax: >-
  type DisasterRecoveryConfigsListNextResponse = ArmDisasterRecoveryListResult &
  { _response: Object }
