name: DisasterRecoveryConfigsListAuthorizationRulesResponse
uid: >-
  @azure/arm-eventhub.DisasterRecoveryConfigsListAuthorizationRulesResponse|latest-stable
package: '@azure/arm-eventhub|latest-stable'
summary: Contains response data for the listAuthorizationRules operation.
fullName: DisasterRecoveryConfigsListAuthorizationRulesResponse
remarks: ''
isPreview: false
isDeprecated: false
syntax: >-
  type DisasterRecoveryConfigsListAuthorizationRulesResponse =
  AuthorizationRuleListResult & { _response: Object }
