name: DisasterRecoveryConfigsCheckNameAvailabilityResponse
uid: >-
  @azure/arm-eventhub.DisasterRecoveryConfigsCheckNameAvailabilityResponse|latest-stable
package: '@azure/arm-eventhub|latest-stable'
summary: Contains response data for the checkNameAvailability operation.
fullName: DisasterRecoveryConfigsCheckNameAvailabilityResponse
remarks: ''
isPreview: false
isDeprecated: false
syntax: >-
  type DisasterRecoveryConfigsCheckNameAvailabilityResponse =
  CheckNameAvailabilityResult & { _response: Object }
