### YamlMime:TSType
name: Logging
uid: '@azure/data-tables.Logging|latest-stable'
package: '@azure/data-tables|latest-stable'
summary: Azure Analytics Logging settings.
fullName: Logging
remarks: ''
isPreview: false
isDeprecated: false
type: interface
properties:
  - name: delete
    uid: '@azure/data-tables.Logging.delete|latest-stable'
    package: '@azure/data-tables|latest-stable'
    summary: Indicates whether all delete requests should be logged.
    fullName: delete
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'delete: boolean'
      return:
        type: boolean
        description: ''
  - name: read
    uid: '@azure/data-tables.Logging.read|latest-stable'
    package: '@azure/data-tables|latest-stable'
    summary: Indicates whether all read requests should be logged.
    fullName: read
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'read: boolean'
      return:
        type: boolean
        description: ''
  - name: retentionPolicy
    uid: '@azure/data-tables.Logging.retentionPolicy|latest-stable'
    package: '@azure/data-tables|latest-stable'
    summary: The retention policy.
    fullName: retentionPolicy
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'retentionPolicy: RetentionPolicy'
      return:
        type: <xref uid="@azure/data-tables.RetentionPolicy" />
        description: ''
  - name: version
    uid: '@azure/data-tables.Logging.version|latest-stable'
    package: '@azure/data-tables|latest-stable'
    summary: The version of Analytics to configure.
    fullName: version
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'version: string'
      return:
        type: string
        description: ''
  - name: write
    uid: '@azure/data-tables.Logging.write|latest-stable'
    package: '@azure/data-tables|latest-stable'
    summary: Indicates whether all write requests should be logged.
    fullName: write
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'write: boolean'
      return:
        type: boolean
        description: ''
