name: LroResourceLocationConfig
uid: '@azure/core-lro.LroResourceLocationConfig|latest-stable'
package: '@azure/core-lro|latest-stable'
summary: >-
  The potential location of the result of the LRO if specified by the LRO
  extension in the swagger.
fullName: LroResourceLocationConfig
remarks: ''
isPreview: false
isDeprecated: false
syntax: >-
  type LroResourceLocationConfig = "azure-async-operation" | "location" |
  "original-uri"
