### YamlMime:TSTypeAlias
name: ConfigurationPatchResponse
uid: '@azure/arm-eventhub.ConfigurationPatchResponse|latest-stable'
package: '@azure/arm-eventhub|latest-stable'
summary: Contains response data for the patch operation.
fullName: ConfigurationPatchResponse
remarks: ''
isPreview: false
isDeprecated: false
syntax: >-
  type ConfigurationPatchResponse = ClusterQuotaConfigurationProperties & {
  _response: Object }
