name: Database
uid: '@azure/cosmos.Database|latest-stable'
package: '@azure/cosmos|latest-stable'
summary: Operations for reading or deleting an existing database.
fullName: Database
remarks: ''
isPreview: false
isDeprecated: false
type: class
constructors:
  - name: Database(CosmosClient, string, ClientContext)
    uid: '@azure/cosmos.Database.constructor|latest-stable'
    package: '@azure/cosmos|latest-stable'
    summary: >
      Returns a new <xref:@azure/cosmos.Database> instance.

      Note: the intention is to get this object from
      <xref:@azure/cosmos.CosmosClient> via `client.database(id)`, not to
      instantiate it yourself.
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: >-
        new Database(client: CosmosClient, id: string, clientContext:
        ClientContext)
      parameters:
        - id: client
          type: <xref uid="@azure/cosmos.CosmosClient" />
          description: ''
        - id: id
          type: string
          description: ''
        - id: clientContext
          type: ClientContext
          description: ''
properties:
  - name: client
    uid: '@azure/cosmos.Database.client|latest-stable'
    package: '@azure/cosmos|latest-stable'
    summary: ''
    fullName: client
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'client: CosmosClient'
      return:
        type: <xref uid="@azure/cosmos.CosmosClient" />
        description: ''
  - name: containers
    uid: '@azure/cosmos.Database.containers|latest-stable'
    package: '@azure/cosmos|latest-stable'
    summary: >
      Used for creating new containers, or querying/reading all containers.

      Use `.database(id)` to read, replace, or delete a specific, existing
      <xref:@azure/cosmos.Database> by id.
    fullName: containers
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'containers: Containers'
      return:
        type: <xref uid="@azure/cosmos.Containers" />
        description: ''
  - name: id
    uid: '@azure/cosmos.Database.id|latest-stable'
    package: '@azure/cosmos|latest-stable'
    summary: ''
    fullName: id
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'id: string'
      return:
        type: string
        description: ''
  - name: url
    uid: '@azure/cosmos.Database.url|latest-stable'
    package: '@azure/cosmos|latest-stable'
    summary: Returns a reference URL to the resource. Used for linking in Permissions.
    fullName: url
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: string url
      return:
        type: string
        description: ''
  - name: users
    uid: '@azure/cosmos.Database.users|latest-stable'
    package: '@azure/cosmos|latest-stable'
    summary: >
      Used for creating new users, or querying/reading all users.

      Use `.user(id)` to read, replace, or delete a specific, existing
      <xref:@azure/cosmos.User> by id.
    fullName: users
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'users: Users'
      return:
        type: <xref uid="@azure/cosmos.Users" />
        description: ''
methods:
  - name: container(string)
    uid: '@azure/cosmos.Database.container|latest-stable'
    package: '@azure/cosmos|latest-stable'
    summary: >
      Used to read, replace, or delete a specific, existing
      <xref:@azure/cosmos.Database> by id.

      Use `.containers` creating new containers, or querying/reading all
      containers.
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'function container(id: string)'
      parameters:
        - id: id
          type: string
          description: ''
      return:
        type: <xref uid="@azure/cosmos.Container" />
        description: ''
  - name: delete(RequestOptions)
    uid: '@azure/cosmos.Database.delete|latest-stable'
    package: '@azure/cosmos|latest-stable'
    summary: Delete the given Database.
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'function delete(options?: RequestOptions)'
      parameters:
        - id: options
          type: <xref uid="@azure/cosmos.RequestOptions" />
          description: ''
      return:
        type: Promise&lt;<xref uid="@azure/cosmos.DatabaseResponse" />&gt;
        description: ''
  - name: read(RequestOptions)
    uid: '@azure/cosmos.Database.read|latest-stable'
    package: '@azure/cosmos|latest-stable'
    summary: Read the definition of the given Database.
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'function read(options?: RequestOptions)'
      parameters:
        - id: options
          type: <xref uid="@azure/cosmos.RequestOptions" />
          description: ''
      return:
        type: Promise&lt;<xref uid="@azure/cosmos.DatabaseResponse" />&gt;
        description: ''
  - name: readOffer(RequestOptions)
    uid: '@azure/cosmos.Database.readOffer|latest-stable'
    package: '@azure/cosmos|latest-stable'
    summary: >-
      Gets offer on database. If none exists, returns an OfferResponse with
      undefined.
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'function readOffer(options?: RequestOptions)'
      parameters:
        - id: options
          type: <xref uid="@azure/cosmos.RequestOptions" />
          description: ''
      return:
        type: Promise&lt;<xref uid="@azure/cosmos.OfferResponse" />&gt;
        description: ''
  - name: user(string)
    uid: '@azure/cosmos.Database.user|latest-stable'
    package: '@azure/cosmos|latest-stable'
    summary: >
      Used to read, replace, or delete a specific, existing
      <xref:@azure/cosmos.User> by id.

      Use `.users` for creating new users, or querying/reading all users.
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'function user(id: string)'
      parameters:
        - id: id
          type: string
          description: ''
      return:
        type: <xref uid="@azure/cosmos.User" />
        description: ''
