name: ConnectionConfig
uid: '@azure/core-amqp.ConnectionConfig|preview'
package: '@azure/core-amqp|preview'
summary: >-
  Describes the connection config object that is created after parsing an
  EventHub or ServiceBus

  connection string.
fullName: ConnectionConfig
remarks: ''
isPreview: false
isDeprecated: false
type: interface
properties:
  - name: connectionString
    uid: '@azure/core-amqp.ConnectionConfig.connectionString|preview'
    package: '@azure/core-amqp|preview'
    summary: '{string} connectionString - The connection string.'
    fullName: connectionString
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'connectionString: string'
      return:
        type: string
        description: ''
  - name: endpoint
    uid: '@azure/core-amqp.ConnectionConfig.endpoint|preview'
    package: '@azure/core-amqp|preview'
    summary: |-
      {string} endpoint - The service bus endpoint
      "sb://<yournamespace>.servicebus.windows.net/".
    fullName: endpoint
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'endpoint: string'
      return:
        type: string
        description: ''
  - name: entityPath
    uid: '@azure/core-amqp.ConnectionConfig.entityPath|preview'
    package: '@azure/core-amqp|preview'
    summary: >-
      {string} entityPath - The name/path of the entity (hub/queue/topic name)
      to which the

      connection needs to happen.
    fullName: entityPath
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'entityPath?: string'
      return:
        type: string
        description: ''
  - name: host
    uid: '@azure/core-amqp.ConnectionConfig.host|preview'
    package: '@azure/core-amqp|preview'
    summary: '{string} host - The host "<yournamespace>.servicebus.windows.net".'
    fullName: host
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'host: string'
      return:
        type: string
        description: ''
  - name: sharedAccessKey
    uid: '@azure/core-amqp.ConnectionConfig.sharedAccessKey|preview'
    package: '@azure/core-amqp|preview'
    summary: '{string} sharedAccessKey - The secret value of the access key.'
    fullName: sharedAccessKey
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'sharedAccessKey: string'
      return:
        type: string
        description: ''
  - name: sharedAccessKeyName
    uid: '@azure/core-amqp.ConnectionConfig.sharedAccessKeyName|preview'
    package: '@azure/core-amqp|preview'
    summary: '{string} sharedAccessKeyName - The name of the access key.'
    fullName: sharedAccessKeyName
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'sharedAccessKeyName: string'
      return:
        type: string
        description: ''
  - name: webSocket
    uid: '@azure/core-amqp.ConnectionConfig.webSocket|preview'
    package: '@azure/core-amqp|preview'
    summary: >-
      {WebSocketImpl} [webSocket] - The WebSocket constructor used to create an
      AMQP connection

      over a WebSocket. In browsers, the built-in WebSocket will be  used by
      default. In Node, a

      TCP socket will be used if a WebSocket constructor is not provided.
    fullName: webSocket
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'webSocket?: WebSocketImpl'
      return:
        type: WebSocketImpl
        description: ''
  - name: webSocketConstructorOptions
    uid: '@azure/core-amqp.ConnectionConfig.webSocketConstructorOptions|preview'
    package: '@azure/core-amqp|preview'
    summary: >-
      {any} [webSocketConstructorOptions] - Options to be passed to the
      WebSocket constructor
    fullName: webSocketConstructorOptions
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'webSocketConstructorOptions?: any'
      return:
        type: any
        description: ''
  - name: webSocketEndpointPath
    uid: '@azure/core-amqp.ConnectionConfig.webSocketEndpointPath|preview'
    package: '@azure/core-amqp|preview'
    summary: >-
      {string} [webSocketEndpointPath] - The path for the endpoint that accepts
      an AMQP

      connection over WebSockets.
    fullName: webSocketEndpointPath
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'webSocketEndpointPath?: string'
      return:
        type: string
        description: ''
