### YamlMime:TSType
name: EnvironmentCredentialOptions
uid: '@azure/identity.EnvironmentCredentialOptions|latest-stable'
package: '@azure/identity|latest-stable'
summary: >-
  Enables authentication to Azure Active Directory depending on the available
  environment variables.

  Defines options for the EnvironmentCredential class.
fullName: EnvironmentCredentialOptions
remarks: ''
isPreview: false
isDeprecated: false
type: interface
properties:
  - name: allowInsecureConnection
    uid: >-
      @azure/identity.EnvironmentCredentialOptions.allowInsecureConnection|latest-stable
    package: '@azure/identity|latest-stable'
    summary: Set to true if the request is sent over HTTP instead of HTTPS
    fullName: allowInsecureConnection
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'allowInsecureConnection?: boolean'
      return:
        type: boolean
        description: ''
  - name: authorityHost
    uid: '@azure/identity.EnvironmentCredentialOptions.authorityHost|latest-stable'
    package: '@azure/identity|latest-stable'
    summary: >-
      The authority host to use for authentication requests.

      Possible values are available through
      <xref:@azure/identity.AzureAuthorityHosts>.

      The default is "https://login.microsoftonline.com".
    fullName: authorityHost
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'authorityHost?: string'
      return:
        type: string
        description: ''
  - name: httpClient
    uid: '@azure/identity.EnvironmentCredentialOptions.httpClient|latest-stable'
    package: '@azure/identity|latest-stable'
    summary: The HttpClient that will be used to send HTTP requests.
    fullName: httpClient
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'httpClient?: HttpClient'
      return:
        type: HttpClient
        description: ''
  - name: proxyOptions
    uid: '@azure/identity.EnvironmentCredentialOptions.proxyOptions|latest-stable'
    package: '@azure/identity|latest-stable'
    summary: Options to configure a proxy for outgoing requests.
    fullName: proxyOptions
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'proxyOptions?: ProxySettings'
      return:
        type: ProxySettings
        description: ''
  - name: redirectOptions
    uid: '@azure/identity.EnvironmentCredentialOptions.redirectOptions|latest-stable'
    package: '@azure/identity|latest-stable'
    summary: Options for how redirect responses are handled.
    fullName: redirectOptions
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'redirectOptions?: RedirectPolicyOptions'
      return:
        type: RedirectPolicyOptions
        description: ''
  - name: retryOptions
    uid: '@azure/identity.EnvironmentCredentialOptions.retryOptions|latest-stable'
    package: '@azure/identity|latest-stable'
    summary: Options that control how to retry failed requests.
    fullName: retryOptions
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'retryOptions?: ExponentialRetryPolicyOptions'
      return:
        type: ExponentialRetryPolicyOptions
        description: ''
  - name: userAgentOptions
    uid: >-
      @azure/identity.EnvironmentCredentialOptions.userAgentOptions|latest-stable
    package: '@azure/identity|latest-stable'
    summary: Options for adding user agent details to outgoing requests.
    fullName: userAgentOptions
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'userAgentOptions?: UserAgentPolicyOptions'
      return:
        type: UserAgentPolicyOptions
        description: ''
extends: <xref uid="@azure/identity.TokenCredentialOptions|latest-stable" />
