name: FileQueryCsvTextConfiguration
uid: '@azure/storage-file-datalake.FileQueryCsvTextConfiguration|preview'
package: '@azure/storage-file-datalake|preview'
summary: Options to query file with CSV format.
fullName: FileQueryCsvTextConfiguration
remarks: ''
isPreview: false
isDeprecated: false
type: interface
properties:
  - name: columnSeparator
    uid: >-
      @azure/storage-file-datalake.FileQueryCsvTextConfiguration.columnSeparator|preview
    package: '@azure/storage-file-datalake|preview'
    summary: Column separator. Default is ",".
    fullName: columnSeparator
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'columnSeparator?: string'
      return:
        type: string
        description: ''
  - name: escapeCharacter
    uid: >-
      @azure/storage-file-datalake.FileQueryCsvTextConfiguration.escapeCharacter|preview
    package: '@azure/storage-file-datalake|preview'
    summary: Escape character.
    fullName: escapeCharacter
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'escapeCharacter?: string'
      return:
        type: string
        description: ''
  - name: fieldQuote
    uid: >-
      @azure/storage-file-datalake.FileQueryCsvTextConfiguration.fieldQuote|preview
    package: '@azure/storage-file-datalake|preview'
    summary: Field quote.
    fullName: fieldQuote
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'fieldQuote?: string'
      return:
        type: string
        description: ''
  - name: hasHeaders
    uid: >-
      @azure/storage-file-datalake.FileQueryCsvTextConfiguration.hasHeaders|preview
    package: '@azure/storage-file-datalake|preview'
    summary: Has headers. Default is false.
    fullName: hasHeaders
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'hasHeaders?: boolean'
      return:
        type: boolean
        description: ''
  - name: kind
    uid: '@azure/storage-file-datalake.FileQueryCsvTextConfiguration.kind|preview'
    package: '@azure/storage-file-datalake|preview'
    summary: Query for a CSV format file.
    fullName: kind
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'kind: "csv"'
      return:
        type: '"csv"'
        description: ''
  - name: recordSeparator
    uid: >-
      @azure/storage-file-datalake.FileQueryCsvTextConfiguration.recordSeparator|preview
    package: '@azure/storage-file-datalake|preview'
    summary: Record separator.
    fullName: recordSeparator
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'recordSeparator: string'
      return:
        type: string
        description: ''
