### YamlMime:TSType
name: GetConfigurationSettingOptions
uid: '@azure/app-configuration.GetConfigurationSettingOptions|latest-stable'
package: '@azure/app-configuration|latest-stable'
summary: Options for getting a ConfigurationSetting.
fullName: GetConfigurationSettingOptions
remarks: ''
isPreview: false
isDeprecated: false
type: interface
properties:
  - name: abortSignal
    uid: >-
      @azure/app-configuration.GetConfigurationSettingOptions.abortSignal|latest-stable
    package: '@azure/app-configuration|latest-stable'
    summary: The signal which can be used to abort requests.
    fullName: abortSignal
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'abortSignal?: AbortSignalLike'
      return:
        type: AbortSignalLike
        description: ''
  - name: acceptDateTime
    uid: >-
      @azure/app-configuration.GetConfigurationSettingOptions.acceptDateTime|latest-stable
    package: '@azure/app-configuration|latest-stable'
    summary: >-
      Requests the server to respond with the state of the resource at the
      specified time.
    fullName: acceptDateTime
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'acceptDateTime?: Date'
      return:
        type: Date
        description: ''
  - name: fields
    uid: >-
      @azure/app-configuration.GetConfigurationSettingOptions.fields|latest-stable
    package: '@azure/app-configuration|latest-stable'
    summary: Which fields to return for each ConfigurationSetting
    fullName: fields
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: >-
        fields?: "key" | "label" | "etag" | "contentType" | "tags" | "value" |
        "isReadOnly" | "lastModified"[]
      return:
        type: >-
          "key" | "label" | "etag" | "contentType" | "tags" | "value" |
          "isReadOnly" | "lastModified"[]
        description: ''
  - name: onlyIfChanged
    uid: >-
      @azure/app-configuration.GetConfigurationSettingOptions.onlyIfChanged|latest-stable
    package: '@azure/app-configuration|latest-stable'
    summary: >-
      Used to perform an operation only if the targeted resource's etag does not
      match the value

      provided.
    fullName: onlyIfChanged
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'onlyIfChanged?: boolean'
      return:
        type: boolean
        description: ''
  - name: requestOptions
    uid: >-
      @azure/app-configuration.GetConfigurationSettingOptions.requestOptions|latest-stable
    package: '@azure/app-configuration|latest-stable'
    summary: Options used when creating and sending HTTP requests for this operation.
    fullName: requestOptions
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'requestOptions?: OperationRequestOptions'
      return:
        type: OperationRequestOptions
        description: ''
  - name: tracingOptions
    uid: >-
      @azure/app-configuration.GetConfigurationSettingOptions.tracingOptions|latest-stable
    package: '@azure/app-configuration|latest-stable'
    summary: Options used when tracing is enabled.
    fullName: tracingOptions
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'tracingOptions?: OperationTracingOptions'
      return:
        type: OperationTracingOptions
        description: ''
extends: OperationOptions
