### YamlMime:TSType
name: ListConfigurationSettingPage
uid: '@azure/app-configuration.ListConfigurationSettingPage|latest-stable'
package: '@azure/app-configuration|latest-stable'
summary: A page of configuration settings and the corresponding HTTP response
fullName: ListConfigurationSettingPage
remarks: ''
isPreview: false
isDeprecated: false
type: interface
properties:
  - name: continuationToken
    uid: >-
      @azure/app-configuration.ListConfigurationSettingPage.continuationToken|latest-stable
    package: '@azure/app-configuration|latest-stable'
    summary: The token that keeps track of where to continue the iterator
    fullName: continuationToken
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'continuationToken?: string'
      return:
        type: string
        description: ''
  - name: items
    uid: '@azure/app-configuration.ListConfigurationSettingPage.items|latest-stable'
    package: '@azure/app-configuration|latest-stable'
    summary: The configuration settings for this page of results.
    fullName: items
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'items: ConfigurationSetting[]'
      return:
        type: >-
          <xref
          uid="@azure/app-configuration.ConfigurationSetting|latest-stable" />[]
        description: ''
extends: >-
  <xref uid="@azure/app-configuration.HttpResponseField|latest-stable"
  />&lt;<xref uid="@azure/app-configuration.SyncTokenHeaderField|latest-stable"
  />&gt;
