### YamlMime:TSType
name: ListSettingsOptions
uid: '@azure/app-configuration.ListSettingsOptions|latest-stable'
package: '@azure/app-configuration|latest-stable'
summary: >-
  Common options for 'list' style APIs in AppConfig used to specify wildcards as
  well as

  the accept date time header.
fullName: ListSettingsOptions
remarks: ''
isPreview: false
isDeprecated: false
type: interface
properties:
  - name: acceptDateTime
    uid: '@azure/app-configuration.ListSettingsOptions.acceptDateTime|latest-stable'
    package: '@azure/app-configuration|latest-stable'
    summary: >-
      Requests the server to respond with the state of the resource at the
      specified time.
    fullName: acceptDateTime
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'acceptDateTime?: Date'
      return:
        type: Date
        description: ''
  - name: fields
    uid: '@azure/app-configuration.ListSettingsOptions.fields|latest-stable'
    package: '@azure/app-configuration|latest-stable'
    summary: Which fields to return for each ConfigurationSetting
    fullName: fields
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: >-
        fields?: "key" | "label" | "etag" | "contentType" | "tags" | "value" |
        "isReadOnly" | "lastModified"[]
      return:
        type: >-
          "key" | "label" | "etag" | "contentType" | "tags" | "value" |
          "isReadOnly" | "lastModified"[]
        description: ''
  - name: keyFilter
    uid: '@azure/app-configuration.ListSettingsOptions.keyFilter|latest-stable'
    package: '@azure/app-configuration|latest-stable'
    summary: >
      Filters for keys. There are two types of matching:

      1. Exact matching. Up to 5 key names are allowed, separated by commas
      (',')

      2. Wildcard matching. A single wildcard expression can be specified.

         | Value        | Matches                               |
         |--------------|---------------------------------------|
         | omitted or * | Matches any key                       |
         | abc          | Matches a key named abc               |
         | abc*         | Matches key names that start with abc |

      These characters are reserved and must be prefixed with backslash in order

      to be specified: * or \\ or ,
    fullName: keyFilter
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'keyFilter?: string'
      return:
        type: string
        description: ''
  - name: labelFilter
    uid: '@azure/app-configuration.ListSettingsOptions.labelFilter|latest-stable'
    package: '@azure/app-configuration|latest-stable'
    summary: |
      Filters for labels. There are two types of matching:
      1. Exact matching. Up to 5 labels are allowed, separated by commas (',')
      2. Wildcard matching. A single wildcard expression can be specified.

         | Value        | Matches                                           |
         |--------------|---------------------------------------------------|
         | omitted or * | Matches any key                                   |
         | %00          | Matches any key without a label                   |
         | prod         | Matches a key with label named prod               |
         | prod*        | Matches key with label names that start with prod |

      These characters are reserved and must be prefixed with backslash in order
      to be specified: * or \\ or ,
    fullName: labelFilter
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'labelFilter?: string'
      return:
        type: string
        description: ''
extends: <xref uid="@azure/app-configuration.OptionalFields|latest-stable" />
