name: TrainingStatus
uid: '@azure/ai-form-recognizer.TrainingStatus|latest-stable'
package: '@azure/ai-form-recognizer|latest-stable'
summary: Defines values for TrainStatus.
fullName: TrainingStatus
remarks: ''
isPreview: false
isDeprecated: false
syntax: type TrainingStatus = "succeeded" | "partiallySucceeded" | "failed"
