name: TrainingOperationState
uid: '@azure/ai-form-recognizer.TrainingOperationState|latest-stable'
package: '@azure/ai-form-recognizer|latest-stable'
summary: The status of a form training operation
fullName: TrainingOperationState
remarks: ''
isPreview: false
isDeprecated: false
syntax: >-
  type TrainingOperationState = PollOperationState<CustomFormModelInfo> & {
  status: ModelStatus }
