### YamlMime:TSType
name: TrainingDocumentInfo
uid: '@azure/ai-form-recognizer.TrainingDocumentInfo|latest-stable'
package: '@azure/ai-form-recognizer|latest-stable'
summary: Report for a custom model training document.
fullName: TrainingDocumentInfo
remarks: ''
isPreview: false
isDeprecated: false
type: interface
properties:
  - name: errors
    uid: '@azure/ai-form-recognizer.TrainingDocumentInfo.errors|latest-stable'
    package: '@azure/ai-form-recognizer|latest-stable'
    summary: List of errors.
    fullName: errors
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'errors: FormRecognizerError[]'
      return:
        type: >-
          <xref
          uid="@azure/ai-form-recognizer.FormRecognizerError|latest-stable" />[]
        description: ''
  - name: modelId
    uid: '@azure/ai-form-recognizer.TrainingDocumentInfo.modelId|latest-stable'
    package: '@azure/ai-form-recognizer|latest-stable'
    summary: The model ID associated with this training document
    fullName: modelId
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'modelId?: string'
      return:
        type: string
        description: ''
  - name: name
    uid: '@azure/ai-form-recognizer.TrainingDocumentInfo.name|latest-stable'
    package: '@azure/ai-form-recognizer|latest-stable'
    summary: Training document name.
    fullName: name
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'name: string'
      return:
        type: string
        description: ''
  - name: pageCount
    uid: '@azure/ai-form-recognizer.TrainingDocumentInfo.pageCount|latest-stable'
    package: '@azure/ai-form-recognizer|latest-stable'
    summary: Total number of pages trained.
    fullName: pageCount
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'pageCount: number'
      return:
        type: number
        description: ''
  - name: status
    uid: '@azure/ai-form-recognizer.TrainingDocumentInfo.status|latest-stable'
    package: '@azure/ai-form-recognizer|latest-stable'
    summary: Status of the training operation.
    fullName: status
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'status: TrainingStatus'
      return:
        type: <xref uid="@azure/ai-form-recognizer.TrainingStatus|latest-stable" />
        description: ''
