name: ListRoleAssignmentsPageSettings
uid: '@azure/keyvault-admin.ListRoleAssignmentsPageSettings|latest-stable'
package: '@azure/keyvault-admin|latest-stable'
summary: Arguments for retrieving the next page of search results.
fullName: ListRoleAssignmentsPageSettings
remarks: ''
isPreview: false
isDeprecated: false
type: interface
properties:
  - name: continuationToken
    uid: >-
      @azure/keyvault-admin.ListRoleAssignmentsPageSettings.continuationToken|latest-stable
    package: '@azure/keyvault-admin|latest-stable'
    summary: |-
      A token used for retrieving the next page of results when the server
      enforces pagination.
    fullName: continuationToken
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'continuationToken?: string'
      return:
        type: string
        description: ''
