### YamlMime:TSType
name: Action
uid: '@azure/arm-servicebus.Action|latest-stable'
package: '@azure/arm-servicebus|latest-stable'
summary: >-
  Represents the filter actions which are allowed for the transformation of a
  message that have

  been matched by a filter expression.
fullName: Action
remarks: ''
isPreview: false
isDeprecated: false
type: interface
properties:
  - name: compatibilityLevel
    uid: '@azure/arm-servicebus.Action.compatibilityLevel|latest-stable'
    package: '@azure/arm-servicebus|latest-stable'
    summary: >-
      This property is reserved for future use. An integer value showing the
      compatibility level,

      currently hard-coded to 20.
    fullName: compatibilityLevel
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'compatibilityLevel?: undefined | number'
      return:
        type: undefined | number
        description: ''
  - name: requiresPreprocessing
    uid: '@azure/arm-servicebus.Action.requiresPreprocessing|latest-stable'
    package: '@azure/arm-servicebus|latest-stable'
    summary: >-
      Value that indicates whether the rule action requires preprocessing.
      Default value: true.
    fullName: requiresPreprocessing
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'requiresPreprocessing?: undefined | false | true'
      return:
        type: undefined | false | true
        description: ''
  - name: sqlExpression
    uid: '@azure/arm-servicebus.Action.sqlExpression|latest-stable'
    package: '@azure/arm-servicebus|latest-stable'
    summary: SQL expression. e.g. MyProperty='ABC'
    fullName: sqlExpression
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'sqlExpression?: undefined | string'
      return:
        type: undefined | string
        description: ''
