### YamlMime:TSTypeAlias
name: DisasterRecoveryConfigsListAuthorizationRulesResponse
uid: >-
  @azure/arm-servicebus.DisasterRecoveryConfigsListAuthorizationRulesResponse|latest-stable
package: '@azure/arm-servicebus|latest-stable'
summary: Contains response data for the listAuthorizationRules operation.
fullName: DisasterRecoveryConfigsListAuthorizationRulesResponse
remarks: ''
isPreview: false
isDeprecated: false
syntax: >-
  type DisasterRecoveryConfigsListAuthorizationRulesResponse =
  SBAuthorizationRuleListResult & { _response: Object }
