### YamlMime:TSTypeAlias
name: DisasterRecoveryConfigsListAuthorizationRulesNextResponse
uid: >-
  @azure/arm-servicebus.DisasterRecoveryConfigsListAuthorizationRulesNextResponse|latest-stable
package: '@azure/arm-servicebus|latest-stable'
summary: Contains response data for the listAuthorizationRulesNext operation.
fullName: DisasterRecoveryConfigsListAuthorizationRulesNextResponse
remarks: ''
isPreview: false
isDeprecated: false
syntax: >-
  type DisasterRecoveryConfigsListAuthorizationRulesNextResponse =
  SBAuthorizationRuleListResult & { _response: Object }
