### YamlMime:TSTypeAlias
name: DisasterRecoveryConfigsListResponse
uid: '@azure/arm-servicebus.DisasterRecoveryConfigsListResponse|latest-stable'
package: '@azure/arm-servicebus|latest-stable'
summary: Contains response data for the list operation.
fullName: DisasterRecoveryConfigsListResponse
remarks: ''
isPreview: false
isDeprecated: false
syntax: >-
  type DisasterRecoveryConfigsListResponse = ArmDisasterRecoveryListResult & {
  _response: Object }
