### YamlMime:TSTypeAlias
name: MigrationConfigsListResponse
uid: '@azure/arm-servicebus.MigrationConfigsListResponse|latest-stable'
package: '@azure/arm-servicebus|latest-stable'
summary: Contains response data for the list operation.
fullName: MigrationConfigsListResponse
remarks: ''
isPreview: false
isDeprecated: false
syntax: >-
  type MigrationConfigsListResponse = MigrationConfigListResult & { _response:
  Object }
