### YamlMime:TSType
name: ShareProtocolSettings
uid: '@azure/storage-file-share.ShareProtocolSettings|preview'
package: '@azure/storage-file-share|preview'
summary: Protocol settings
fullName: ShareProtocolSettings
remarks: ''
isPreview: false
isDeprecated: false
type: interface
properties:
  - name: smb
    uid: '@azure/storage-file-share.ShareProtocolSettings.smb|preview'
    package: '@azure/storage-file-share|preview'
    summary: Settings for SMB protocol.
    fullName: smb
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'smb?: ShareSmbSettings'
      return:
        type: <xref uid="@azure/storage-file-share.ShareSmbSettings|preview" />
        description: ''
