### YamlMime:TSType
name: AppConfigurationKeyValueDeletedEventData
uid: '@azure/eventgrid.AppConfigurationKeyValueDeletedEventData|latest-stable'
package: '@azure/eventgrid|latest-stable'
summary: >-
  Schema of the Data property of an EventGridEvent for a
  Microsoft.AppConfiguration.KeyValueDeleted event.
fullName: AppConfigurationKeyValueDeletedEventData
remarks: ''
isPreview: false
isDeprecated: false
type: interface
properties:
  - name: etag
    uid: >-
      @azure/eventgrid.AppConfigurationKeyValueDeletedEventData.etag|latest-stable
    package: '@azure/eventgrid|latest-stable'
    summary: The etag representing the key-value that was deleted.
    fullName: etag
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'etag: string'
      return:
        type: string
        description: ''
  - name: key
    uid: >-
      @azure/eventgrid.AppConfigurationKeyValueDeletedEventData.key|latest-stable
    package: '@azure/eventgrid|latest-stable'
    summary: The key used to identify the key-value that was deleted.
    fullName: key
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'key: string'
      return:
        type: string
        description: ''
  - name: label
    uid: >-
      @azure/eventgrid.AppConfigurationKeyValueDeletedEventData.label|latest-stable
    package: '@azure/eventgrid|latest-stable'
    summary: The label, if any, used to identify the key-value that was deleted.
    fullName: label
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'label: string'
      return:
        type: string
        description: ''
  - name: syncToken
    uid: >-
      @azure/eventgrid.AppConfigurationKeyValueDeletedEventData.syncToken|latest-stable
    package: '@azure/eventgrid|latest-stable'
    summary: The sync token representing the server state after the event.
    fullName: syncToken
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'syncToken: string'
      return:
        type: string
        description: ''
