name: CommunicationCloudEnvironmentModel
uid: '@azure/eventgrid.CommunicationCloudEnvironmentModel|latest-stable'
package: '@azure/eventgrid|latest-stable'
summary: >-
  Defines values for CommunicationCloudEnvironmentModel. \

  KnownCommunicationCloudEnvironmentModel can be used interchangeably with
  CommunicationCloudEnvironmentModel,
   this enum contains the known values that the service supports.
  ### Known values supported by the service

  **public** \

  **dod** \

  **gcch**
fullName: CommunicationCloudEnvironmentModel
remarks: ''
isPreview: false
isDeprecated: false
syntax: type CommunicationCloudEnvironmentModel = string
