### YamlMime:TSType
name: BlobQueryJsonTextConfiguration
uid: '@azure/storage-blob.BlobQueryJsonTextConfiguration|latest-stable'
package: '@azure/storage-blob|latest-stable'
summary: Options to query blob with JSON format.
fullName: BlobQueryJsonTextConfiguration
remarks: ''
isPreview: false
isDeprecated: false
type: interface
properties:
  - name: kind
    uid: '@azure/storage-blob.BlobQueryJsonTextConfiguration.kind|latest-stable'
    package: '@azure/storage-blob|latest-stable'
    summary: Query for a JSON format blob.
    fullName: kind
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'kind: "json"'
      return:
        type: '"json"'
        description: ''
  - name: recordSeparator
    uid: >-
      @azure/storage-blob.BlobQueryJsonTextConfiguration.recordSeparator|latest-stable
    package: '@azure/storage-blob|latest-stable'
    summary: Record separator.
    fullName: recordSeparator
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'recordSeparator: string'
      return:
        type: string
        description: ''
