name: ConfigurationStoresListByResourceGroupResponse
uid: >-
  @azure/arm-appconfiguration.ConfigurationStoresListByResourceGroupResponse|latest-stable
package: '@azure/arm-appconfiguration|latest-stable'
summary: Contains response data for the listByResourceGroup operation.
fullName: ConfigurationStoresListByResourceGroupResponse
remarks: ''
isPreview: false
isDeprecated: false
syntax: >-
  type ConfigurationStoresListByResourceGroupResponse =
  ConfigurationStoreListResult & { _response: Object }
