### YamlMime:TSTypeAlias
name: ConfigurationStoresCreateResponse
uid: '@azure/arm-appconfiguration.ConfigurationStoresCreateResponse|latest-stable'
package: '@azure/arm-appconfiguration|latest-stable'
summary: Contains response data for the create operation.
fullName: ConfigurationStoresCreateResponse
remarks: ''
isPreview: false
isDeprecated: false
syntax: >-
  type ConfigurationStoresCreateResponse = ConfigurationStore & { _response:
  Object }
