### YamlMime:TSTypeAlias
name: ConfigurationStoresListByResourceGroupNextResponse
uid: >-
  @azure/arm-appconfiguration.ConfigurationStoresListByResourceGroupNextResponse|latest-stable
package: '@azure/arm-appconfiguration|latest-stable'
summary: Contains response data for the listByResourceGroupNext operation.
fullName: ConfigurationStoresListByResourceGroupNextResponse
remarks: ''
isPreview: false
isDeprecated: false
syntax: >-
  type ConfigurationStoresListByResourceGroupNextResponse =
  ConfigurationStoreListResult & { _response: Object }
