name: ConfigurationStoresGetResponse
uid: '@azure/arm-appconfiguration.ConfigurationStoresGetResponse|latest-stable'
package: '@azure/arm-appconfiguration|latest-stable'
summary: Contains response data for the get operation.
fullName: ConfigurationStoresGetResponse
remarks: ''
isPreview: false
isDeprecated: false
syntax: >-
  type ConfigurationStoresGetResponse = ConfigurationStore & { _response: Object
  }
