name: ConfigurationStoresBeginUpdateResponse
uid: >-
  @azure/arm-appconfiguration.ConfigurationStoresBeginUpdateResponse|latest-stable
package: '@azure/arm-appconfiguration|latest-stable'
summary: Contains response data for the beginUpdate operation.
fullName: ConfigurationStoresBeginUpdateResponse
remarks: ''
isPreview: false
isDeprecated: false
syntax: >-
  type ConfigurationStoresBeginUpdateResponse = ConfigurationStore & {
  _response: Object }
