### YamlMime:TSType
name: ConfigurationStoreUpdateParameters
uid: '@azure/arm-appconfiguration.ConfigurationStoreUpdateParameters|latest-stable'
package: '@azure/arm-appconfiguration|latest-stable'
summary: The parameters for updating a configuration store.
fullName: ConfigurationStoreUpdateParameters
remarks: ''
isPreview: false
isDeprecated: false
type: interface
properties:
  - name: disableLocalAuth
    uid: >-
      @azure/arm-appconfiguration.ConfigurationStoreUpdateParameters.disableLocalAuth|latest-stable
    package: '@azure/arm-appconfiguration|latest-stable'
    summary: Disables all authentication methods other than AAD authentication.
    fullName: disableLocalAuth
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'disableLocalAuth?: undefined | false | true'
      return:
        type: undefined | false | true
        description: ''
  - name: encryption
    uid: >-
      @azure/arm-appconfiguration.ConfigurationStoreUpdateParameters.encryption|latest-stable
    package: '@azure/arm-appconfiguration|latest-stable'
    summary: The encryption settings of the configuration store.
    fullName: encryption
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'encryption?: EncryptionProperties'
      return:
        type: >-
          <xref
          uid="@azure/arm-appconfiguration.EncryptionProperties|latest-stable"
          />
        description: ''
  - name: identity
    uid: >-
      @azure/arm-appconfiguration.ConfigurationStoreUpdateParameters.identity|latest-stable
    package: '@azure/arm-appconfiguration|latest-stable'
    summary: The managed identity information for the configuration store.
    fullName: identity
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'identity?: ResourceIdentity'
      return:
        type: >-
          <xref uid="@azure/arm-appconfiguration.ResourceIdentity|latest-stable"
          />
        description: ''
  - name: publicNetworkAccess
    uid: >-
      @azure/arm-appconfiguration.ConfigurationStoreUpdateParameters.publicNetworkAccess|latest-stable
    package: '@azure/arm-appconfiguration|latest-stable'
    summary: >-
      Control permission for data plane traffic coming from public networks
      while private endpoint

      is enabled. Possible values include: 'Enabled', 'Disabled'
    fullName: publicNetworkAccess
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'publicNetworkAccess?: PublicNetworkAccess'
      return:
        type: >-
          <xref
          uid="@azure/arm-appconfiguration.PublicNetworkAccess|latest-stable" />
        description: ''
  - name: sku
    uid: >-
      @azure/arm-appconfiguration.ConfigurationStoreUpdateParameters.sku|latest-stable
    package: '@azure/arm-appconfiguration|latest-stable'
    summary: The SKU of the configuration store.
    fullName: sku
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'sku?: Sku'
      return:
        type: <xref uid="@azure/arm-appconfiguration.Sku|latest-stable" />
        description: ''
  - name: tags
    uid: >-
      @azure/arm-appconfiguration.ConfigurationStoreUpdateParameters.tags|latest-stable
    package: '@azure/arm-appconfiguration|latest-stable'
    summary: The ARM resource tags.
    fullName: tags
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'tags?: undefined | [key: string]: string'
      return:
        type: 'undefined | [key: string]: string'
        description: ''
