### YamlMime:TSType
name: ConfigurationStore
uid: '@azure/arm-appconfiguration.ConfigurationStore|latest-stable'
package: '@azure/arm-appconfiguration|latest-stable'
summary: >-
  The configuration store along with all resource properties. The Configuration
  Store will have

  all information to begin utilizing it.
fullName: ConfigurationStore
remarks: ''
isPreview: false
isDeprecated: false
type: interface
properties:
  - name: creationDate
    uid: '@azure/arm-appconfiguration.ConfigurationStore.creationDate|latest-stable'
    package: '@azure/arm-appconfiguration|latest-stable'
    summary: >-
      The creation date of configuration store.

      **NOTE: This property will not be serialized. It can only be populated by
      the server.**
    fullName: creationDate
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'creationDate?: Date'
      return:
        type: Date
        description: ''
  - name: disableLocalAuth
    uid: >-
      @azure/arm-appconfiguration.ConfigurationStore.disableLocalAuth|latest-stable
    package: '@azure/arm-appconfiguration|latest-stable'
    summary: Disables all authentication methods other than AAD authentication.
    fullName: disableLocalAuth
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'disableLocalAuth?: undefined | false | true'
      return:
        type: undefined | false | true
        description: ''
  - name: encryption
    uid: '@azure/arm-appconfiguration.ConfigurationStore.encryption|latest-stable'
    package: '@azure/arm-appconfiguration|latest-stable'
    summary: The encryption settings of the configuration store.
    fullName: encryption
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'encryption?: EncryptionProperties'
      return:
        type: <xref uid="@azure/arm-appconfiguration.EncryptionProperties" />
        description: ''
  - name: endpoint
    uid: '@azure/arm-appconfiguration.ConfigurationStore.endpoint|latest-stable'
    package: '@azure/arm-appconfiguration|latest-stable'
    summary: >-
      The DNS endpoint where the configuration store API will be available.

      **NOTE: This property will not be serialized. It can only be populated by
      the server.**
    fullName: endpoint
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'endpoint?: undefined | string'
      return:
        type: undefined | string
        description: ''
  - name: id
    uid: '@azure/arm-appconfiguration.ConfigurationStore.id|latest-stable'
    package: '@azure/arm-appconfiguration|latest-stable'
    summary: >-
      Fully qualified resource ID for the resource. Ex -

      /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}

      **NOTE: This property will not be serialized. It can only be populated by
      the server.**
    fullName: id
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'id?: undefined | string'
      return:
        type: undefined | string
        description: ''
  - name: identity
    uid: '@azure/arm-appconfiguration.ConfigurationStore.identity|latest-stable'
    package: '@azure/arm-appconfiguration|latest-stable'
    summary: The managed identity information, if configured.
    fullName: identity
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'identity?: ResourceIdentity'
      return:
        type: <xref uid="@azure/arm-appconfiguration.ResourceIdentity" />
        description: ''
  - name: location
    uid: '@azure/arm-appconfiguration.ConfigurationStore.location|latest-stable'
    package: '@azure/arm-appconfiguration|latest-stable'
    summary: The geo-location where the resource lives
    fullName: location
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'location: string'
      return:
        type: string
        description: ''
  - name: name
    uid: '@azure/arm-appconfiguration.ConfigurationStore.name|latest-stable'
    package: '@azure/arm-appconfiguration|latest-stable'
    summary: >-
      The name of the resource

      **NOTE: This property will not be serialized. It can only be populated by
      the server.**
    fullName: name
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'name?: undefined | string'
      return:
        type: undefined | string
        description: ''
  - name: privateEndpointConnections
    uid: >-
      @azure/arm-appconfiguration.ConfigurationStore.privateEndpointConnections|latest-stable
    package: '@azure/arm-appconfiguration|latest-stable'
    summary: >-
      The list of private endpoint connections that are set up for this
      resource.

      **NOTE: This property will not be serialized. It can only be populated by
      the server.**
    fullName: privateEndpointConnections
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'privateEndpointConnections?: PrivateEndpointConnectionReference[]'
      return:
        type: >-
          <xref
          uid="@azure/arm-appconfiguration.PrivateEndpointConnectionReference"
          />[]
        description: ''
  - name: provisioningState
    uid: >-
      @azure/arm-appconfiguration.ConfigurationStore.provisioningState|latest-stable
    package: '@azure/arm-appconfiguration|latest-stable'
    summary: >-
      The provisioning state of the configuration store. Possible values
      include: 'Creating',

      'Updating', 'Deleting', 'Succeeded', 'Failed', 'Canceled'

      **NOTE: This property will not be serialized. It can only be populated by
      the server.**
    fullName: provisioningState
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'provisioningState?: ProvisioningState'
      return:
        type: <xref uid="@azure/arm-appconfiguration.ProvisioningState" />
        description: ''
  - name: publicNetworkAccess
    uid: >-
      @azure/arm-appconfiguration.ConfigurationStore.publicNetworkAccess|latest-stable
    package: '@azure/arm-appconfiguration|latest-stable'
    summary: >-
      Control permission for data plane traffic coming from public networks
      while private endpoint

      is enabled. Possible values include: 'Enabled', 'Disabled'
    fullName: publicNetworkAccess
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'publicNetworkAccess?: PublicNetworkAccess'
      return:
        type: <xref uid="@azure/arm-appconfiguration.PublicNetworkAccess" />
        description: ''
  - name: sku
    uid: '@azure/arm-appconfiguration.ConfigurationStore.sku|latest-stable'
    package: '@azure/arm-appconfiguration|latest-stable'
    summary: The sku of the configuration store.
    fullName: sku
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'sku: Sku'
      return:
        type: <xref uid="@azure/arm-appconfiguration.Sku" />
        description: ''
  - name: systemData
    uid: '@azure/arm-appconfiguration.ConfigurationStore.systemData|latest-stable'
    package: '@azure/arm-appconfiguration|latest-stable'
    summary: Resource system metadata.
    fullName: systemData
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'systemData?: SystemData'
      return:
        type: <xref uid="@azure/arm-appconfiguration.SystemData" />
        description: ''
  - name: tags
    uid: '@azure/arm-appconfiguration.ConfigurationStore.tags|latest-stable'
    package: '@azure/arm-appconfiguration|latest-stable'
    summary: Resource tags.
    fullName: tags
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'tags?: undefined | [key: string]: string'
      return:
        type: 'undefined | [key: string]: string'
        description: ''
  - name: type
    uid: '@azure/arm-appconfiguration.ConfigurationStore.type|latest-stable'
    package: '@azure/arm-appconfiguration|latest-stable'
    summary: >-
      The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or

      "Microsoft.Storage/storageAccounts"

      **NOTE: This property will not be serialized. It can only be populated by
      the server.**
    fullName: type
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'type?: undefined | string'
      return:
        type: undefined | string
        description: ''
extends: <xref uid="@azure/arm-appconfiguration.TrackedResource" />
