name: ConfigurationStoresListResponse
uid: '@azure/arm-appconfiguration.ConfigurationStoresListResponse|latest-stable'
package: '@azure/arm-appconfiguration|latest-stable'
summary: Contains response data for the list operation.
fullName: ConfigurationStoresListResponse
remarks: ''
isPreview: false
isDeprecated: false
syntax: >-
  type ConfigurationStoresListResponse = ConfigurationStoreListResult & {
  _response: Object }
