name: PrivateEndpointConnectionsListByConfigurationStoreNextResponse
uid: >-
  @azure/arm-appconfiguration.PrivateEndpointConnectionsListByConfigurationStoreNextResponse|latest-stable
package: '@azure/arm-appconfiguration|latest-stable'
summary: Contains response data for the listByConfigurationStoreNext operation.
fullName: PrivateEndpointConnectionsListByConfigurationStoreNextResponse
remarks: ''
isPreview: false
isDeprecated: false
syntax: >-
  type PrivateEndpointConnectionsListByConfigurationStoreNextResponse =
  PrivateEndpointConnectionListResult & { _response: Object }
