name: PrivateLinkResourcesListByConfigurationStoreResponse
uid: >-
  @azure/arm-appconfiguration.PrivateLinkResourcesListByConfigurationStoreResponse|latest-stable
package: '@azure/arm-appconfiguration|latest-stable'
summary: Contains response data for the listByConfigurationStore operation.
fullName: PrivateLinkResourcesListByConfigurationStoreResponse
remarks: ''
isPreview: false
isDeprecated: false
syntax: >-
  type PrivateLinkResourcesListByConfigurationStoreResponse =
  PrivateLinkResourceListResult & { _response: Object }
