name: PrivateLinkResourcesListByConfigurationStoreNextResponse
uid: >-
  @azure/arm-appconfiguration.PrivateLinkResourcesListByConfigurationStoreNextResponse|latest-stable
package: '@azure/arm-appconfiguration|latest-stable'
summary: Contains response data for the listByConfigurationStoreNext operation.
fullName: PrivateLinkResourcesListByConfigurationStoreNextResponse
remarks: ''
isPreview: false
isDeprecated: false
syntax: >-
  type PrivateLinkResourcesListByConfigurationStoreNextResponse =
  PrivateLinkResourceListResult & { _response: Object }
