### YamlMime:TSType
name: DisasterRecoveryConfigsListKeysOptionalParams
uid: '@azure/arm-servicebus.DisasterRecoveryConfigsListKeysOptionalParams|preview'
package: '@azure/arm-servicebus|preview'
summary: Optional parameters.
fullName: DisasterRecoveryConfigsListKeysOptionalParams
remarks: ''
isPreview: false
isDeprecated: false
type: interface
properties:
  - name: abortSignal
    uid: >-
      @azure/arm-servicebus.DisasterRecoveryConfigsListKeysOptionalParams.abortSignal|preview
    package: '@azure/arm-servicebus|preview'
    summary: The signal which can be used to abort requests.
    fullName: abortSignal
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'abortSignal?: AbortSignalLike'
      return:
        type: AbortSignalLike
        description: ''
  - name: onResponse
    uid: >-
      @azure/arm-servicebus.DisasterRecoveryConfigsListKeysOptionalParams.onResponse|preview
    package: '@azure/arm-servicebus|preview'
    summary: |-
      A function to be called each time a response is received from the server
      while performing the requested operation.
      May be called multiple times.
    fullName: onResponse
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'onResponse?: RawResponseCallback'
      return:
        type: RawResponseCallback
        description: ''
  - name: requestOptions
    uid: >-
      @azure/arm-servicebus.DisasterRecoveryConfigsListKeysOptionalParams.requestOptions|preview
    package: '@azure/arm-servicebus|preview'
    summary: Options used when creating and sending HTTP requests for this operation.
    fullName: requestOptions
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'requestOptions?: OperationRequestOptions'
      return:
        type: OperationRequestOptions
        description: ''
  - name: serializerOptions
    uid: >-
      @azure/arm-servicebus.DisasterRecoveryConfigsListKeysOptionalParams.serializerOptions|preview
    package: '@azure/arm-servicebus|preview'
    summary: Options to override serialization/de-serialization behavior.
    fullName: serializerOptions
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'serializerOptions?: SerializerOptions'
      return:
        type: SerializerOptions
        description: ''
  - name: tracingOptions
    uid: >-
      @azure/arm-servicebus.DisasterRecoveryConfigsListKeysOptionalParams.tracingOptions|preview
    package: '@azure/arm-servicebus|preview'
    summary: Options used when tracing is enabled.
    fullName: tracingOptions
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'tracingOptions?: OperationTracingOptions'
      return:
        type: OperationTracingOptions
        description: ''
extends: OperationOptions
