### YamlMime:TSTypeAlias
name: DisasterRecoveryConfigsListKeysResponse
uid: '@azure/arm-servicebus.DisasterRecoveryConfigsListKeysResponse|preview'
package: '@azure/arm-servicebus|preview'
summary: Contains response data for the listKeys operation.
fullName: DisasterRecoveryConfigsListKeysResponse
remarks: ''
isPreview: false
isDeprecated: false
syntax: type DisasterRecoveryConfigsListKeysResponse = AccessKeys
