### YamlMime:TSTypeAlias
name: MigrationConfigsCreateAndStartMigrationResponse
uid: '@azure/arm-servicebus.MigrationConfigsCreateAndStartMigrationResponse|preview'
package: '@azure/arm-servicebus|preview'
summary: Contains response data for the createAndStartMigration operation.
fullName: MigrationConfigsCreateAndStartMigrationResponse
remarks: ''
isPreview: false
isDeprecated: false
syntax: >-
  type MigrationConfigsCreateAndStartMigrationResponse =
  MigrationConfigProperties
