### YamlMime:TSTypeAlias
name: MigrationConfigsBeginCreateAndStartMigrationResponse
uid: >-
  @azure/arm-servicebus.MigrationConfigsBeginCreateAndStartMigrationResponse|preview
package: '@azure/arm-servicebus|preview'
summary: Contains response data for the beginCreateAndStartMigration operation.
fullName: MigrationConfigsBeginCreateAndStartMigrationResponse
remarks: ''
isPreview: false
isDeprecated: false
syntax: >-
  type MigrationConfigsBeginCreateAndStartMigrationResponse =
  MigrationConfigProperties & { _response: Object }
