### YamlMime:TSType
name: MigrationConfigs
uid: '@azure/arm-servicebus.MigrationConfigs|preview'
package: '@azure/arm-servicebus|preview'
summary: Interface representing a MigrationConfigs.
fullName: MigrationConfigs
remarks: ''
isPreview: false
isDeprecated: false
type: interface
methods:
  - name: >-
      beginCreateAndStartMigration(string, string, MigrationConfigurationName,
      MigrationConfigProperties,
      MigrationConfigsCreateAndStartMigrationOptionalParams)
    uid: >-
      @azure/arm-servicebus.MigrationConfigs.beginCreateAndStartMigration|preview
    package: '@azure/arm-servicebus|preview'
    summary: >-
      Creates Migration configuration and starts migration of entities from
      Standard to Premium namespace
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: >-
        function beginCreateAndStartMigration(resourceGroupName: string,
        namespaceName: string, configName: MigrationConfigurationName,
        parameters: MigrationConfigProperties, options?:
        MigrationConfigsCreateAndStartMigrationOptionalParams)
      parameters:
        - id: resourceGroupName
          type: string
          description: Name of the Resource group within the Azure subscription.
        - id: namespaceName
          type: string
          description: The namespace name
        - id: configName
          type: >-
            <xref uid="@azure/arm-servicebus.MigrationConfigurationName|preview"
            />
          description: The configuration name. Should always be "$default".
        - id: parameters
          type: >-
            <xref uid="@azure/arm-servicebus.MigrationConfigProperties|preview"
            />
          description: Parameters required to create Migration Configuration
        - id: options
          type: >-
            <xref
            uid="@azure/arm-servicebus.MigrationConfigsCreateAndStartMigrationOptionalParams|preview"
            />
          description: |
            The options parameters.
      return:
        type: >-
          Promise&lt;PollerLike&lt;PollOperationState&lt;<xref
          uid="@azure/arm-servicebus.MigrationConfigsCreateAndStartMigrationResponse|preview"
          />&gt;, <xref
          uid="@azure/arm-servicebus.MigrationConfigsCreateAndStartMigrationResponse|preview"
          />&gt;&gt;
        description: ''
  - name: >-
      beginCreateAndStartMigrationAndWait(string, string,
      MigrationConfigurationName, MigrationConfigProperties,
      MigrationConfigsCreateAndStartMigrationOptionalParams)
    uid: >-
      @azure/arm-servicebus.MigrationConfigs.beginCreateAndStartMigrationAndWait|preview
    package: '@azure/arm-servicebus|preview'
    summary: >-
      Creates Migration configuration and starts migration of entities from
      Standard to Premium namespace
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: >-
        function beginCreateAndStartMigrationAndWait(resourceGroupName: string,
        namespaceName: string, configName: MigrationConfigurationName,
        parameters: MigrationConfigProperties, options?:
        MigrationConfigsCreateAndStartMigrationOptionalParams)
      parameters:
        - id: resourceGroupName
          type: string
          description: Name of the Resource group within the Azure subscription.
        - id: namespaceName
          type: string
          description: The namespace name
        - id: configName
          type: >-
            <xref uid="@azure/arm-servicebus.MigrationConfigurationName|preview"
            />
          description: The configuration name. Should always be "$default".
        - id: parameters
          type: >-
            <xref uid="@azure/arm-servicebus.MigrationConfigProperties|preview"
            />
          description: Parameters required to create Migration Configuration
        - id: options
          type: >-
            <xref
            uid="@azure/arm-servicebus.MigrationConfigsCreateAndStartMigrationOptionalParams|preview"
            />
          description: |
            The options parameters.
      return:
        type: >-
          Promise&lt;<xref
          uid="@azure/arm-servicebus.MigrationConfigsCreateAndStartMigrationResponse|preview"
          />&gt;
        description: ''
  - name: >-
      completeMigration(string, string, MigrationConfigurationName,
      MigrationConfigsCompleteMigrationOptionalParams)
    uid: '@azure/arm-servicebus.MigrationConfigs.completeMigration|preview'
    package: '@azure/arm-servicebus|preview'
    summary: >-
      This operation Completes Migration of entities by pointing the connection
      strings to Premium

      namespace and any entities created after the operation will be under
      Premium Namespace.

      CompleteMigration operation will fail when entity migration is
      in-progress.
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: >-
        function completeMigration(resourceGroupName: string, namespaceName:
        string, configName: MigrationConfigurationName, options?:
        MigrationConfigsCompleteMigrationOptionalParams)
      parameters:
        - id: resourceGroupName
          type: string
          description: Name of the Resource group within the Azure subscription.
        - id: namespaceName
          type: string
          description: The namespace name
        - id: configName
          type: >-
            <xref uid="@azure/arm-servicebus.MigrationConfigurationName|preview"
            />
          description: The configuration name. Should always be "$default".
        - id: options
          type: >-
            <xref
            uid="@azure/arm-servicebus.MigrationConfigsCompleteMigrationOptionalParams|preview"
            />
          description: |
            The options parameters.
      return:
        type: Promise&lt;void&gt;
        description: ''
  - name: >-
      delete(string, string, MigrationConfigurationName,
      MigrationConfigsDeleteOptionalParams)
    uid: '@azure/arm-servicebus.MigrationConfigs.delete|preview'
    package: '@azure/arm-servicebus|preview'
    summary: Deletes a MigrationConfiguration
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: >-
        function delete(resourceGroupName: string, namespaceName: string,
        configName: MigrationConfigurationName, options?:
        MigrationConfigsDeleteOptionalParams)
      parameters:
        - id: resourceGroupName
          type: string
          description: Name of the Resource group within the Azure subscription.
        - id: namespaceName
          type: string
          description: The namespace name
        - id: configName
          type: >-
            <xref uid="@azure/arm-servicebus.MigrationConfigurationName|preview"
            />
          description: The configuration name. Should always be "$default".
        - id: options
          type: >-
            <xref
            uid="@azure/arm-servicebus.MigrationConfigsDeleteOptionalParams|preview"
            />
          description: |
            The options parameters.
      return:
        type: Promise&lt;void&gt;
        description: ''
  - name: >-
      get(string, string, MigrationConfigurationName,
      MigrationConfigsGetOptionalParams)
    uid: '@azure/arm-servicebus.MigrationConfigs.get|preview'
    package: '@azure/arm-servicebus|preview'
    summary: Retrieves Migration Config
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: >-
        function get(resourceGroupName: string, namespaceName: string,
        configName: MigrationConfigurationName, options?:
        MigrationConfigsGetOptionalParams)
      parameters:
        - id: resourceGroupName
          type: string
          description: Name of the Resource group within the Azure subscription.
        - id: namespaceName
          type: string
          description: The namespace name
        - id: configName
          type: >-
            <xref uid="@azure/arm-servicebus.MigrationConfigurationName|preview"
            />
          description: The configuration name. Should always be "$default".
        - id: options
          type: >-
            <xref
            uid="@azure/arm-servicebus.MigrationConfigsGetOptionalParams|preview"
            />
          description: |
            The options parameters.
      return:
        type: >-
          Promise&lt;<xref
          uid="@azure/arm-servicebus.MigrationConfigsGetResponse|preview" />&gt;
        description: ''
  - name: list(string, string, MigrationConfigsListOptionalParams)
    uid: '@azure/arm-servicebus.MigrationConfigs.list|preview'
    package: '@azure/arm-servicebus|preview'
    summary: Gets all migrationConfigurations
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: >-
        function list(resourceGroupName: string, namespaceName: string,
        options?: MigrationConfigsListOptionalParams)
      parameters:
        - id: resourceGroupName
          type: string
          description: Name of the Resource group within the Azure subscription.
        - id: namespaceName
          type: string
          description: The namespace name
        - id: options
          type: >-
            <xref
            uid="@azure/arm-servicebus.MigrationConfigsListOptionalParams|preview"
            />
          description: |
            The options parameters.
      return:
        type: >-
          PagedAsyncIterableIterator&lt;<xref
          uid="@azure/arm-servicebus.MigrationConfigProperties|preview" />&gt;
        description: ''
  - name: >-
      revert(string, string, MigrationConfigurationName,
      MigrationConfigsRevertOptionalParams)
    uid: '@azure/arm-servicebus.MigrationConfigs.revert|preview'
    package: '@azure/arm-servicebus|preview'
    summary: This operation reverts Migration
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: >-
        function revert(resourceGroupName: string, namespaceName: string,
        configName: MigrationConfigurationName, options?:
        MigrationConfigsRevertOptionalParams)
      parameters:
        - id: resourceGroupName
          type: string
          description: Name of the Resource group within the Azure subscription.
        - id: namespaceName
          type: string
          description: The namespace name
        - id: configName
          type: >-
            <xref uid="@azure/arm-servicebus.MigrationConfigurationName|preview"
            />
          description: The configuration name. Should always be "$default".
        - id: options
          type: >-
            <xref
            uid="@azure/arm-servicebus.MigrationConfigsRevertOptionalParams|preview"
            />
          description: |
            The options parameters.
      return:
        type: Promise&lt;void&gt;
        description: ''
