### YamlMime:TSType
name: MigrationConfigListResult
uid: '@azure/arm-servicebus.MigrationConfigListResult|preview'
package: '@azure/arm-servicebus|preview'
summary: The result of the List migrationConfigurations operation.
fullName: MigrationConfigListResult
remarks: ''
isPreview: false
isDeprecated: false
type: interface
properties:
  - name: nextLink
    uid: '@azure/arm-servicebus.MigrationConfigListResult.nextLink|preview'
    package: '@azure/arm-servicebus|preview'
    summary: >-
      Link to the next set of results. Not empty if Value contains incomplete
      list of migrationConfigurations

      NOTE: This property will not be serialized. It can only be populated by
      the server.
    fullName: nextLink
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'nextLink?: undefined | string'
      return:
        type: undefined | string
        description: ''
  - name: value
    uid: '@azure/arm-servicebus.MigrationConfigListResult.value|preview'
    package: '@azure/arm-servicebus|preview'
    summary: List of Migration Configs
    fullName: value
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'value?: MigrationConfigProperties[]'
      return:
        type: >-
          <xref uid="@azure/arm-servicebus.MigrationConfigProperties|preview"
          />[]
        description: ''
