### YamlMime:TSTypeAlias
name: MigrationConfigProperties
uid: '@azure/arm-servicebus.MigrationConfigProperties|preview'
package: '@azure/arm-servicebus|preview'
summary: Single item in List or Get Migration Config operation
fullName: MigrationConfigProperties
remarks: ''
isPreview: false
isDeprecated: false
syntax: >-
  type MigrationConfigProperties = Resource & { migrationState: Object,
  pendingReplicationOperationsCount: Object, postMigrationName: Object,
  provisioningState: Object, targetNamespace: Object }
