### YamlMime:TSType
name: LroConfig
uid: '@azure/arm-storage.LroConfig|preview'
package: '@azure/arm-storage|preview'
summary: >-
  The configuration of a LRO to determine how to perform polling and checking
  whether the operation has completed.
fullName: LroConfig
remarks: ''
isPreview: false
isDeprecated: false
type: interface
properties:
  - name: mode
    uid: '@azure/arm-storage.LroConfig.mode|preview'
    package: '@azure/arm-storage|preview'
    summary: The LRO mode
    fullName: mode
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'mode?: LroMode'
      return:
        type: <xref uid="@azure/arm-storage.LroMode" />
        description: ''
  - name: resourceLocation
    uid: '@azure/arm-storage.LroConfig.resourceLocation|preview'
    package: '@azure/arm-storage|preview'
    summary: The path of a provisioned resource
    fullName: resourceLocation
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'resourceLocation?: undefined | string'
      return:
        type: undefined | string
        description: ''
