name: LroResourceLocationConfig
uid: '@azure/arm-storage.LroResourceLocationConfig|preview'
package: '@azure/arm-storage|preview'
summary: >-
  The potential location of the result of the LRO if specified by the LRO
  extension in the swagger.
fullName: LroResourceLocationConfig
remarks: ''
isPreview: false
isDeprecated: false
syntax: >-
  type LroResourceLocationConfig = "azure-async-operation" | "location" |
  "original-uri"
