### YamlMime:TSType
name: PollerConfig
uid: '@azure/arm-storage.PollerConfig|preview'
package: '@azure/arm-storage|preview'
summary: ''
fullName: PollerConfig
remarks: ''
isPreview: false
isDeprecated: false
type: interface
properties:
  - name: intervalInMs
    uid: '@azure/arm-storage.PollerConfig.intervalInMs|preview'
    package: '@azure/arm-storage|preview'
    summary: ''
    fullName: intervalInMs
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'intervalInMs: number'
      return:
        type: number
        description: ''
