name: ProtocolSettings
uid: '@azure/arm-storage.ProtocolSettings|preview'
package: '@azure/arm-storage|preview'
summary: Protocol settings for file service
fullName: ProtocolSettings
remarks: ''
isPreview: false
isDeprecated: false
type: interface
properties:
  - name: smb
    uid: '@azure/arm-storage.ProtocolSettings.smb|preview'
    package: '@azure/arm-storage|preview'
    summary: Setting for SMB protocol
    fullName: smb
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'smb?: SmbSetting'
      return:
        type: <xref uid="@azure/arm-storage.SmbSetting" />
        description: ''
