name: AddConfigurationSettingParam
uid: '@azure/app-configuration.AddConfigurationSettingParam|latest-stable'
package: '@azure/app-configuration|latest-stable'
summary: Parameters for adding a new configuration setting
fullName: AddConfigurationSettingParam<T>
remarks: ''
isPreview: false
isDeprecated: false
syntax: type AddConfigurationSettingParam<T> = ConfigurationSettingParam<T>
