### YamlMime:TSType
name: AppConfigurationClientOptions
uid: '@azure/app-configuration.AppConfigurationClientOptions|latest-stable'
package: '@azure/app-configuration|latest-stable'
summary: Provides configuration options for AppConfigurationClient.
fullName: AppConfigurationClientOptions
remarks: ''
isPreview: false
isDeprecated: false
type: interface
properties:
  - name: retryOptions
    uid: >-
      @azure/app-configuration.AppConfigurationClientOptions.retryOptions|latest-stable
    package: '@azure/app-configuration|latest-stable'
    summary: Options that control how to retry failed requests.
    fullName: retryOptions
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'retryOptions?: RetryOptions'
      return:
        type: <xref uid="@azure/app-configuration.RetryOptions" />
        description: ''
  - name: userAgentOptions
    uid: >-
      @azure/app-configuration.AppConfigurationClientOptions.userAgentOptions|latest-stable
    package: '@azure/app-configuration|latest-stable'
    summary: Options for adding user agent details to outgoing requests.
    fullName: userAgentOptions
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'userAgentOptions?: UserAgentOptions'
      return:
        type: UserAgentOptions
        description: ''
