name: ConfigurationSetting
uid: '@azure/app-configuration.ConfigurationSetting|latest-stable'
package: '@azure/app-configuration|latest-stable'
summary: |-
  Configuration setting with extra metadata from the server, indicating
  its etag, whether it is currently readOnly and when it was last modified.
fullName: ConfigurationSetting<T>
remarks: ''
isPreview: false
isDeprecated: false
syntax: >-
  type ConfigurationSetting<T> = ConfigurationSettingParam<T> & { isReadOnly:
  boolean, lastModified: Date }
