name: ConfigurationSettingResponse
uid: '@azure/app-configuration.ConfigurationSettingResponse|latest-stable'
package: '@azure/app-configuration|latest-stable'
summary: >-
  Standard base response for getting, deleting or updating a configuration
  setting
fullName: ConfigurationSettingResponse<HeadersT>
remarks: ''
isPreview: false
isDeprecated: false
syntax: >-
  type ConfigurationSettingResponse<HeadersT> = ConfigurationSetting &
  HttpResponseField<HeadersT> & Pick<HeadersT>
