name: ConfigurationSettingParam
uid: '@azure/app-configuration.ConfigurationSettingParam|latest-stable'
package: '@azure/app-configuration|latest-stable'
summary: Necessary fields for updating or creating a new configuration setting
fullName: ConfigurationSettingParam<T>
remarks: ''
isPreview: false
isDeprecated: false
syntax: >-
  type ConfigurationSettingParam<T> = ConfigurationSettingId & { contentType:
  string, tags: Object } & T extends string ? { value?: string; } : { value: T;
  }
