### YamlMime:TSType
name: DeleteConfigurationSettingResponse
uid: '@azure/app-configuration.DeleteConfigurationSettingResponse|latest-stable'
package: '@azure/app-configuration|latest-stable'
summary: Response from deleting a ConfigurationSetting.
fullName: DeleteConfigurationSettingResponse
remarks: ''
isPreview: false
isDeprecated: false
type: interface
properties:
  - name: statusCode
    uid: >-
      @azure/app-configuration.DeleteConfigurationSettingResponse.statusCode|latest-stable
    package: '@azure/app-configuration|latest-stable'
    summary: The HTTP status code for the response
    fullName: statusCode
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'statusCode: number'
      return:
        type: number
        description: ''
  - name: syncToken
    uid: >-
      @azure/app-configuration.DeleteConfigurationSettingResponse.syncToken|latest-stable
    package: '@azure/app-configuration|latest-stable'
    summary: >-
      Enables real-time consistency between requests by providing the returned
      value in the next

      request made to the server.
    fullName: syncToken
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'syncToken?: string'
      return:
        type: string
        description: ''
extends: <xref uid="@azure/app-configuration.SyncTokenHeaderField" />
