name: ListConfigurationSettingsOptions
uid: '@azure/app-configuration.ListConfigurationSettingsOptions|latest-stable'
package: '@azure/app-configuration|latest-stable'
summary: >-
  Options for listConfigurationSettings that allow for filtering based on keys,
  labels and other fields.

  Also provides `fields` which allows you to selectively choose which fields are
  populated in the

  result.
fullName: ListConfigurationSettingsOptions
remarks: ''
isPreview: false
isDeprecated: false
type: interface
properties:
  - name: abortSignal
    uid: >-
      @azure/app-configuration.ListConfigurationSettingsOptions.abortSignal|latest-stable
    package: '@azure/app-configuration|latest-stable'
    summary: The signal which can be used to abort requests.
    fullName: abortSignal
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'abortSignal?: AbortSignalLike'
      return:
        type: AbortSignalLike
        description: ''
  - name: acceptDateTime
    uid: >-
      @azure/app-configuration.ListConfigurationSettingsOptions.acceptDateTime|latest-stable
    package: '@azure/app-configuration|latest-stable'
    summary: >-
      Requests the server to respond with the state of the resource at the
      specified time.
    fullName: acceptDateTime
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'acceptDateTime?: Date'
      return:
        type: Date
        description: ''
  - name: fields
    uid: >-
      @azure/app-configuration.ListConfigurationSettingsOptions.fields|latest-stable
    package: '@azure/app-configuration|latest-stable'
    summary: Which fields to return for each ConfigurationSetting
    fullName: fields
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: >-
        fields?: "key" | "label" | "etag" | "contentType" | "tags" | "value" |
        "isReadOnly" | "lastModified"[]
      return:
        type: >-
          "key" | "label" | "etag" | "contentType" | "tags" | "value" |
          "isReadOnly" | "lastModified"[]
        description: ''
  - name: keyFilter
    uid: >-
      @azure/app-configuration.ListConfigurationSettingsOptions.keyFilter|latest-stable
    package: '@azure/app-configuration|latest-stable'
    summary: >
      Filters for keys. There are two types of matching:

      1. Exact matching. Up to 5 key names are allowed, separated by commas
      (',')

      2. Wildcard matching. A single wildcard expression can be specified.

         | Value        | Matches                               |
         |--------------|---------------------------------------|
         | omitted or * | Matches any key                       |
         | abc          | Matches a key named abc               |
         | abc*         | Matches key names that start with abc |

      These characters are reserved and must be prefixed with backslash in order

      to be specified: * or \\ or ,
    fullName: keyFilter
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'keyFilter?: string'
      return:
        type: string
        description: ''
  - name: labelFilter
    uid: >-
      @azure/app-configuration.ListConfigurationSettingsOptions.labelFilter|latest-stable
    package: '@azure/app-configuration|latest-stable'
    summary: |
      Filters for labels. There are two types of matching:
      1. Exact matching. Up to 5 labels are allowed, separated by commas (',')
      2. Wildcard matching. A single wildcard expression can be specified.

         | Value        | Matches                                           |
         |--------------|---------------------------------------------------|
         | omitted or * | Matches any key                                   |
         | %00          | Matches any key without a label                   |
         | prod         | Matches a key with label named prod               |
         | prod*        | Matches key with label names that start with prod |

      These characters are reserved and must be prefixed with backslash in order
      to be specified: * or \\ or ,
    fullName: labelFilter
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'labelFilter?: string'
      return:
        type: string
        description: ''
  - name: requestOptions
    uid: >-
      @azure/app-configuration.ListConfigurationSettingsOptions.requestOptions|latest-stable
    package: '@azure/app-configuration|latest-stable'
    summary: Options used when creating and sending HTTP requests for this operation.
    fullName: requestOptions
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'requestOptions?: OperationRequestOptions'
      return:
        type: OperationRequestOptions
        description: ''
  - name: tracingOptions
    uid: >-
      @azure/app-configuration.ListConfigurationSettingsOptions.tracingOptions|latest-stable
    package: '@azure/app-configuration|latest-stable'
    summary: Options used when tracing is enabled.
    fullName: tracingOptions
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'tracingOptions?: OperationTracingOptions'
      return:
        type: OperationTracingOptions
        description: ''
extends: OperationOptions
