name: PageSettings
uid: '@azure/app-configuration.PageSettings|latest-stable'
package: '@azure/app-configuration|latest-stable'
summary: An interface that tracks the settings for paged iteration
fullName: PageSettings
remarks: ''
isPreview: false
isDeprecated: false
type: interface
properties:
  - name: continuationToken
    uid: '@azure/app-configuration.PageSettings.continuationToken|latest-stable'
    package: '@azure/app-configuration|latest-stable'
    summary: The token that keeps track of where to continue the iterator
    fullName: continuationToken
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'continuationToken?: string'
      return:
        type: string
        description: ''
