### YamlMime:TSTypeAlias
name: SetConfigurationSettingParam
uid: '@azure/app-configuration.SetConfigurationSettingParam|latest-stable'
package: '@azure/app-configuration|latest-stable'
summary: Parameters for creating or updating a new configuration setting
fullName: SetConfigurationSettingParam<T>
remarks: ''
isPreview: false
isDeprecated: false
syntax: type SetConfigurationSettingParam<T> = ConfigurationSettingParam<T>
