### YamlMime:TSType
name: SemanticSettings
uid: '@azure/search-documents.SemanticSettings|preview'
package: '@azure/search-documents|preview'
summary: Defines parameters for a search index that influence semantic capabilities.
fullName: SemanticSettings
remarks: ''
isPreview: false
isDeprecated: false
type: interface
properties:
  - name: configurations
    uid: '@azure/search-documents.SemanticSettings.configurations|preview'
    package: '@azure/search-documents|preview'
    summary: The semantic configurations for the index.
    fullName: configurations
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'configurations?: SemanticConfiguration[]'
      return:
        type: <xref uid="@azure/search-documents.SemanticConfiguration|preview" />[]
        description: ''
