### YamlMime:TSType
name: SemanticConfiguration
uid: '@azure/search-documents.SemanticConfiguration|preview'
package: '@azure/search-documents|preview'
summary: >-
  Defines a specific configuration to be used in the context of semantic
  capabilities.
fullName: SemanticConfiguration
remarks: ''
isPreview: false
isDeprecated: false
type: interface
properties:
  - name: name
    uid: '@azure/search-documents.SemanticConfiguration.name|preview'
    package: '@azure/search-documents|preview'
    summary: The name of the semantic configuration.
    fullName: name
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'name: string'
      return:
        type: string
        description: ''
  - name: prioritizedFields
    uid: '@azure/search-documents.SemanticConfiguration.prioritizedFields|preview'
    package: '@azure/search-documents|preview'
    summary: >-
      Describes the title, content, and keyword fields to be used for semantic
      ranking, captions, highlights, and answers. At least one of the three sub
      properties (titleField, prioritizedKeywordsFields and
      prioritizedContentFields) need to be set.
    fullName: prioritizedFields
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'prioritizedFields: PrioritizedFields'
      return:
        type: <xref uid="@azure/search-documents.PrioritizedFields|preview" />
        description: ''
