name: DisasterRecoveryConfigsCreateOrUpdateResponse
uid: >-
  @azure/arm-servicebus.DisasterRecoveryConfigsCreateOrUpdateResponse|latest-stable
package: '@azure/arm-servicebus|latest-stable'
summary: Contains response data for the createOrUpdate operation.
fullName: DisasterRecoveryConfigsCreateOrUpdateResponse
remarks: ''
isPreview: false
isDeprecated: false
syntax: >-
  type DisasterRecoveryConfigsCreateOrUpdateResponse = ArmDisasterRecovery & {
  _response: Object }
