name: DisasterRecoveryConfigsCheckNameAvailabilityMethodResponse
uid: >-
  @azure/arm-servicebus.DisasterRecoveryConfigsCheckNameAvailabilityMethodResponse|latest-stable
package: '@azure/arm-servicebus|latest-stable'
summary: Contains response data for the checkNameAvailabilityMethod operation.
fullName: DisasterRecoveryConfigsCheckNameAvailabilityMethodResponse
remarks: ''
isPreview: false
isDeprecated: false
syntax: >-
  type DisasterRecoveryConfigsCheckNameAvailabilityMethodResponse =
  CheckNameAvailabilityResult & { _response: Object }
