### YamlMime:TSTypeAlias
name: DisasterRecoveryConfigsListKeysResponse
uid: '@azure/arm-servicebus.DisasterRecoveryConfigsListKeysResponse|latest-stable'
package: '@azure/arm-servicebus|latest-stable'
summary: Contains response data for the listKeys operation.
fullName: DisasterRecoveryConfigsListKeysResponse
remarks: ''
isPreview: false
isDeprecated: false
syntax: >-
  type DisasterRecoveryConfigsListKeysResponse = AccessKeys & { _response:
  Object }
