### YamlMime:TSType
name: Pipeline
uid: '@azure/storage-queue.Pipeline|preview'
package: '@azure/storage-queue|preview'
summary: >-
  A Pipeline class containing HTTP request policies.

  You can create a default Pipeline by calling newPipeline().

  Or you can create a Pipeline with your own policies by the constructor of
  Pipeline.

  Refer to newPipeline() and provided policies as reference before

  implementing your customized Pipeline.
fullName: Pipeline
remarks: ''
isPreview: false
isDeprecated: false
type: class
constructors:
  - name: Pipeline(RequestPolicyFactory[], PipelineOptions)
    uid: '@azure/storage-queue.Pipeline.constructor|preview'
    package: '@azure/storage-queue|preview'
    summary: >-
      Creates an instance of Pipeline. Customize HTTPClient by implementing
      IHttpClient interface.
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: >-
        new Pipeline(factories: RequestPolicyFactory[], options?:
        PipelineOptions)
      parameters:
        - id: factories
          type: RequestPolicyFactory[]
          description: '-'
        - id: options
          type: <xref uid="@azure/storage-queue.PipelineOptions" />
          description: |
            -
properties:
  - name: factories
    uid: '@azure/storage-queue.Pipeline.factories|preview'
    package: '@azure/storage-queue|preview'
    summary: A list of chained request policy factories.
    fullName: factories
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'factories: RequestPolicyFactory[]'
      return:
        type: RequestPolicyFactory[]
        description: ''
  - name: options
    uid: '@azure/storage-queue.Pipeline.options|preview'
    package: '@azure/storage-queue|preview'
    summary: Configures pipeline logger and HTTP client.
    fullName: options
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'options: PipelineOptions'
      return:
        type: <xref uid="@azure/storage-queue.PipelineOptions" />
        description: ''
methods:
  - name: toServiceClientOptions()
    uid: '@azure/storage-queue.Pipeline.toServiceClientOptions|preview'
    package: '@azure/storage-queue|preview'
    summary: |-
      Transfers Pipeline object to ServiceClientOptions object which required by
      ServiceClient constructor.
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: function toServiceClientOptions()
      return:
        type: ServiceClientOptions
        description: The ServiceClientOptions object from this Pipeline.
