name: DisasterRecoveryConfigsCreateOrUpdateResponse
uid: '@azure/arm-servicebus.DisasterRecoveryConfigsCreateOrUpdateResponse|preview'
package: '@azure/arm-servicebus|preview'
summary: Contains response data for the createOrUpdate operation.
fullName: DisasterRecoveryConfigsCreateOrUpdateResponse
remarks: ''
isPreview: false
isDeprecated: false
syntax: type DisasterRecoveryConfigsCreateOrUpdateResponse = ArmDisasterRecovery
