### YamlMime:TSTypeAlias
name: DisasterRecoveryConfigsListAuthorizationRulesNextResponse
uid: >-
  @azure/arm-servicebus.DisasterRecoveryConfigsListAuthorizationRulesNextResponse|preview
package: '@azure/arm-servicebus|preview'
summary: Contains response data for the listAuthorizationRulesNext operation.
fullName: DisasterRecoveryConfigsListAuthorizationRulesNextResponse
remarks: ''
isPreview: false
isDeprecated: false
syntax: >-
  type DisasterRecoveryConfigsListAuthorizationRulesNextResponse =
  SBAuthorizationRuleListResult
