name: DisasterRecoveryConfigsGetAuthorizationRuleResponse
uid: >-
  @azure/arm-servicebus.DisasterRecoveryConfigsGetAuthorizationRuleResponse|preview
package: '@azure/arm-servicebus|preview'
summary: Contains response data for the getAuthorizationRule operation.
fullName: DisasterRecoveryConfigsGetAuthorizationRuleResponse
remarks: ''
isPreview: false
isDeprecated: false
syntax: type DisasterRecoveryConfigsGetAuthorizationRuleResponse = SBAuthorizationRule
