name: DisasterRecoveryConfigsGetResponse
uid: '@azure/arm-servicebus.DisasterRecoveryConfigsGetResponse|preview'
package: '@azure/arm-servicebus|preview'
summary: Contains response data for the get operation.
fullName: DisasterRecoveryConfigsGetResponse
remarks: ''
isPreview: false
isDeprecated: false
syntax: type DisasterRecoveryConfigsGetResponse = ArmDisasterRecovery
