### YamlMime:TSTypeAlias
name: DisasterRecoveryConfigsCheckNameAvailabilityResponse
uid: >-
  @azure/arm-servicebus.DisasterRecoveryConfigsCheckNameAvailabilityResponse|preview
package: '@azure/arm-servicebus|preview'
summary: Contains response data for the checkNameAvailability operation.
fullName: DisasterRecoveryConfigsCheckNameAvailabilityResponse
remarks: ''
isPreview: false
isDeprecated: false
syntax: >-
  type DisasterRecoveryConfigsCheckNameAvailabilityResponse =
  CheckNameAvailabilityResult
