name: MigrationConfigsListResponse
uid: '@azure/arm-servicebus.MigrationConfigsListResponse|preview'
package: '@azure/arm-servicebus|preview'
summary: Contains response data for the list operation.
fullName: MigrationConfigsListResponse
remarks: ''
isPreview: false
isDeprecated: false
syntax: type MigrationConfigsListResponse = MigrationConfigListResult
