### YamlMime:TSType
name: FileQueryJsonTextConfiguration
uid: '@azure/storage-file-datalake.FileQueryJsonTextConfiguration|preview'
package: '@azure/storage-file-datalake|preview'
summary: Options to query file with JSON format.
fullName: FileQueryJsonTextConfiguration
remarks: ''
isPreview: false
isDeprecated: false
type: interface
properties:
  - name: kind
    uid: '@azure/storage-file-datalake.FileQueryJsonTextConfiguration.kind|preview'
    package: '@azure/storage-file-datalake|preview'
    summary: Query for a JSON format file.
    fullName: kind
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'kind: "json"'
      return:
        type: '"json"'
        description: ''
  - name: recordSeparator
    uid: >-
      @azure/storage-file-datalake.FileQueryJsonTextConfiguration.recordSeparator|preview
    package: '@azure/storage-file-datalake|preview'
    summary: Record separator.
    fullName: recordSeparator
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'recordSeparator: string'
      return:
        type: string
        description: ''
