### YamlMime:TSType
name: PageSettings
uid: '@azure/core-paging.PageSettings|latest-stable'
package: '@azure/core-paging|latest-stable'
summary: An interface that tracks the settings for paged iteration
fullName: PageSettings
remarks: ''
isPreview: false
isDeprecated: false
type: interface
properties:
  - name: continuationToken
    uid: '@azure/core-paging.PageSettings.continuationToken|latest-stable'
    package: '@azure/core-paging|latest-stable'
    summary: The token that keeps track of where to continue the iterator
    fullName: continuationToken
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'continuationToken?: string'
      return:
        type: string
        description: ''
  - name: maxPageSize
    uid: '@azure/core-paging.PageSettings.maxPageSize|latest-stable'
    package: '@azure/core-paging|latest-stable'
    summary: The size of the page during paged iteration
    fullName: maxPageSize
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'maxPageSize?: number'
      return:
        type: number
        description: ''
