### YamlMime:TSTypeAlias
name: ConfigurationGetResponse
uid: '@azure/arm-eventhub.ConfigurationGetResponse|preview'
package: '@azure/arm-eventhub|preview'
summary: Contains response data for the get operation.
fullName: ConfigurationGetResponse
remarks: ''
isPreview: false
isDeprecated: false
syntax: type ConfigurationGetResponse = ClusterQuotaConfigurationProperties
