### YamlMime:TSTypeAlias
name: DisasterRecoveryConfigsListResponse
uid: '@azure/arm-eventhub.DisasterRecoveryConfigsListResponse|preview'
package: '@azure/arm-eventhub|preview'
summary: Contains response data for the list operation.
fullName: DisasterRecoveryConfigsListResponse
remarks: ''
isPreview: false
isDeprecated: false
syntax: type DisasterRecoveryConfigsListResponse = ArmDisasterRecoveryListResult
